-- B0 schedule foundation: one stable logical occurrence may retain multiple
-- immutable physical generations while its current pointer changes.
-- Flyway owns the transaction; all source guards precede DDL.

DO $$
BEGIN
    -- Existing rows have no authoritative assignment/snapshot provenance. A
    -- guessed backfill would make the old schedule history ambiguous.
    IF EXISTS (SELECT 1 FROM schedule_items) THEN
        RAISE EXCEPTION
            'V17 cannot migrate legacy schedule_items without assignment provenance';
    END IF;
    IF EXISTS (SELECT 1 FROM lessons) THEN
        RAISE EXCEPTION
            'V17 cannot migrate legacy lessons without immutable occurrence snapshots';
    END IF;
    IF EXISTS (SELECT 1 FROM schedule_one_off_lessons) THEN
        RAISE EXCEPTION
            'V17 cannot migrate legacy one-off lessons without occurrence provenance';
    END IF;
END
$$;

-- Do not use the newly-added literal in a same-transaction predicate. It is
-- available to application writes after this migration commits.
ALTER TYPE lesson_status ADD VALUE IF NOT EXISTS 'transferred';

ALTER TABLE lessons
    DROP CONSTRAINT IF EXISTS lessons_schedule_item_id_date_key,
    DROP CONSTRAINT IF EXISTS lessons_schedule_item_id_fkey;

ALTER TABLE schedule_one_off_lessons
    DROP CONSTRAINT IF EXISTS uq_one_off_slot;

ALTER TABLE schedule_items
    ADD COLUMN assignment_id BIGINT NOT NULL,
    ADD CONSTRAINT schedule_items_assignment_positive_chk
        CHECK (assignment_id > 0);

CREATE TABLE lesson_occurrences
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    schedule_item_id    BIGINT,
    one_off_lesson_id   BIGINT,
    occurrence_date     DATE         NOT NULL,
    assignment_id       BIGINT       NOT NULL,
    group_id            BIGINT       NOT NULL,
    subject_id          BIGINT       NOT NULL,
    semester_id         BIGINT       NOT NULL,
    assigned_teacher_id BIGINT       NOT NULL,
    lesson_type         VARCHAR(16)  NOT NULL,
    generation          BIGINT       NOT NULL DEFAULT 1,
    revision            BIGINT       NOT NULL DEFAULT 1,
    current_lesson_id   BIGINT,
    created_at          TIMESTAMPTZ  NOT NULL DEFAULT NOW(),

    CONSTRAINT lesson_occurrences_id_positive_chk CHECK (id > 0),
    CONSTRAINT lesson_occurrences_assignment_positive_chk CHECK (assignment_id > 0),
    CONSTRAINT lesson_occurrences_group_positive_chk CHECK (group_id > 0),
    CONSTRAINT lesson_occurrences_subject_positive_chk CHECK (subject_id > 0),
    CONSTRAINT lesson_occurrences_semester_positive_chk CHECK (semester_id > 0),
    CONSTRAINT lesson_occurrences_teacher_positive_chk CHECK (assigned_teacher_id > 0),
    CONSTRAINT lesson_occurrences_type_chk
        CHECK (lesson_type IN ('lecture', 'practice', 'lab')),
    CONSTRAINT lesson_occurrences_generation_positive_chk CHECK (generation > 0),
    CONSTRAINT lesson_occurrences_revision_positive_chk CHECK (revision > 0),
    CONSTRAINT lesson_occurrences_origin_xor_chk
        CHECK ((schedule_item_id IS NOT NULL AND one_off_lesson_id IS NULL)
            OR (schedule_item_id IS NULL AND one_off_lesson_id IS NOT NULL)),
    CONSTRAINT lesson_occurrences_schedule_item_fk
        FOREIGN KEY (schedule_item_id) REFERENCES schedule_items (id) ON DELETE RESTRICT,
    CONSTRAINT lesson_occurrences_one_off_fk
        FOREIGN KEY (one_off_lesson_id)
        REFERENCES schedule_one_off_lessons (id) ON DELETE RESTRICT,
    CONSTRAINT lesson_occurrences_id_generation_uq UNIQUE (id, generation)
);

CREATE UNIQUE INDEX uq_lesson_occurrences_recurring_origin
    ON lesson_occurrences (schedule_item_id, occurrence_date)
    WHERE schedule_item_id IS NOT NULL;

CREATE UNIQUE INDEX uq_lesson_occurrences_one_off_origin
    ON lesson_occurrences (one_off_lesson_id)
    WHERE one_off_lesson_id IS NOT NULL;

ALTER TABLE lessons
    ALTER COLUMN schedule_item_id DROP NOT NULL,
    ADD COLUMN one_off_lesson_id     BIGINT,
    ADD COLUMN occurrence_id         BIGINT NOT NULL,
    ADD COLUMN assignment_id         BIGINT NOT NULL,
    ADD COLUMN group_id              BIGINT NOT NULL,
    ADD COLUMN subject_id            BIGINT NOT NULL,
    ADD COLUMN semester_id           BIGINT NOT NULL,
    ADD COLUMN assigned_teacher_id   BIGINT NOT NULL,
    ADD COLUMN lesson_type           VARCHAR(16) NOT NULL,
    ADD COLUMN lesson_number         SMALLINT NOT NULL,
    ADD COLUMN start_time            TIME NOT NULL,
    ADD COLUMN end_time              TIME NOT NULL,
    ADD COLUMN room_snapshot         VARCHAR(64),
    ADD COLUMN generation            BIGINT NOT NULL DEFAULT 1,
    ADD COLUMN revision              BIGINT NOT NULL DEFAULT 1;

ALTER TABLE schedule_one_off_lessons
    ADD COLUMN physical_lesson_id BIGINT,
    ADD CONSTRAINT schedule_one_off_id_positive_chk CHECK (id > 0),
    ADD CONSTRAINT schedule_one_off_group_positive_chk CHECK (group_id > 0),
    ADD CONSTRAINT schedule_one_off_subject_positive_chk CHECK (subject_id > 0),
    ADD CONSTRAINT schedule_one_off_semester_positive_chk CHECK (semester_id > 0),
    ADD CONSTRAINT schedule_one_off_created_by_positive_chk CHECK (created_by > 0),
    ADD CONSTRAINT schedule_one_off_identity_uq
        UNIQUE (id, group_id, subject_id, semester_id, date, lesson_number);

ALTER TABLE lessons
    ADD CONSTRAINT lessons_id_occurrence_uq UNIQUE (id, occurrence_id),
    ADD CONSTRAINT lessons_occurrence_fk
        FOREIGN KEY (occurrence_id)
        REFERENCES lesson_occurrences (id) ON DELETE RESTRICT
        DEFERRABLE INITIALLY DEFERRED,
    ADD CONSTRAINT lessons_schedule_item_fk
        FOREIGN KEY (schedule_item_id) REFERENCES schedule_items (id) ON DELETE RESTRICT,
    ADD CONSTRAINT lessons_one_off_fk
        FOREIGN KEY (one_off_lesson_id)
        REFERENCES schedule_one_off_lessons (id) ON DELETE RESTRICT,
    ADD CONSTRAINT lessons_occurrence_positive_chk CHECK (occurrence_id > 0),
    ADD CONSTRAINT lessons_assignment_positive_chk CHECK (assignment_id > 0),
    ADD CONSTRAINT lessons_group_positive_chk CHECK (group_id > 0),
    ADD CONSTRAINT lessons_subject_positive_chk CHECK (subject_id > 0),
    ADD CONSTRAINT lessons_semester_positive_chk CHECK (semester_id > 0),
    ADD CONSTRAINT lessons_teacher_positive_chk CHECK (assigned_teacher_id > 0),
    ADD CONSTRAINT lessons_type_chk CHECK (lesson_type IN ('lecture', 'practice', 'lab')),
    ADD CONSTRAINT lessons_number_chk CHECK (lesson_number BETWEEN 1 AND 8),
    ADD CONSTRAINT lessons_generation_positive_chk CHECK (generation > 0),
    ADD CONSTRAINT lessons_revision_positive_chk CHECK (revision > 0),
    ADD CONSTRAINT lessons_time_order_chk CHECK (end_time > start_time),
    ADD CONSTRAINT lessons_origin_xor_chk
        CHECK ((schedule_item_id IS NOT NULL AND one_off_lesson_id IS NULL)
            OR (schedule_item_id IS NULL AND one_off_lesson_id IS NOT NULL));

CREATE UNIQUE INDEX uq_lessons_included_physical_slot
    ON lessons (group_id, date, lesson_number)
    WHERE status IN ('planned', 'active', 'closed');

CREATE UNIQUE INDEX uq_lessons_included_occurrence
    ON lessons (occurrence_id)
    WHERE status IN ('planned', 'active', 'closed');

CREATE INDEX idx_lessons_occurrence_history
    ON lessons (occurrence_id, generation, revision, date);

CREATE OR REPLACE FUNCTION validate_lesson_physical_snapshot()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    occurrence_record lesson_occurrences%ROWTYPE;
BEGIN
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'physical lessons are retained; use a lifecycle state';
    END IF;

    SELECT * INTO occurrence_record
    FROM lesson_occurrences
    WHERE id = NEW.occurrence_id;
    IF NOT FOUND THEN
        RAISE EXCEPTION 'lesson occurrence % does not exist', NEW.occurrence_id;
    END IF;

    IF NEW.occurrence_id IS DISTINCT FROM occurrence_record.id
       OR NEW.schedule_item_id IS DISTINCT FROM occurrence_record.schedule_item_id
       OR NEW.one_off_lesson_id IS DISTINCT FROM occurrence_record.one_off_lesson_id
       OR NEW.assignment_id IS DISTINCT FROM occurrence_record.assignment_id
       OR NEW.group_id IS DISTINCT FROM occurrence_record.group_id
       OR NEW.subject_id IS DISTINCT FROM occurrence_record.subject_id
       OR NEW.semester_id IS DISTINCT FROM occurrence_record.semester_id
       OR NEW.assigned_teacher_id IS DISTINCT FROM occurrence_record.assigned_teacher_id
       OR NEW.lesson_type IS DISTINCT FROM occurrence_record.lesson_type THEN
        RAISE EXCEPTION 'physical lesson identity snapshot does not match its occurrence';
    END IF;

    IF TG_OP = 'UPDATE'
       AND (NEW.id IS DISTINCT FROM OLD.id
            OR NEW.schedule_item_id IS DISTINCT FROM OLD.schedule_item_id
            OR NEW.one_off_lesson_id IS DISTINCT FROM OLD.one_off_lesson_id
            OR NEW.occurrence_id IS DISTINCT FROM OLD.occurrence_id
            OR NEW.assignment_id IS DISTINCT FROM OLD.assignment_id
            OR NEW.group_id IS DISTINCT FROM OLD.group_id
            OR NEW.subject_id IS DISTINCT FROM OLD.subject_id
            OR NEW.semester_id IS DISTINCT FROM OLD.semester_id
            OR NEW.assigned_teacher_id IS DISTINCT FROM OLD.assigned_teacher_id
            OR NEW.lesson_type IS DISTINCT FROM OLD.lesson_type
            OR NEW.date IS DISTINCT FROM OLD.date
            OR NEW.lesson_number IS DISTINCT FROM OLD.lesson_number
            OR NEW.start_time IS DISTINCT FROM OLD.start_time
            OR NEW.end_time IS DISTINCT FROM OLD.end_time
            OR NEW.room_snapshot IS DISTINCT FROM OLD.room_snapshot
            OR NEW.generation IS DISTINCT FROM OLD.generation) THEN
        RAISE EXCEPTION 'physical lesson identity snapshot is immutable';
    END IF;
    IF TG_OP = 'UPDATE' AND NEW.revision < OLD.revision THEN
        RAISE EXCEPTION 'physical lesson revision cannot move backwards';
    END IF;

    RETURN NEW;
END
$$;

CREATE TRIGGER lessons_history_guard_trg
    BEFORE INSERT OR UPDATE OR DELETE ON lessons
    FOR EACH ROW
    EXECUTE FUNCTION validate_lesson_physical_snapshot();

CREATE OR REPLACE FUNCTION protect_occurrence_identity()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    IF NEW.schedule_item_id IS DISTINCT FROM OLD.schedule_item_id
       OR NEW.one_off_lesson_id IS DISTINCT FROM OLD.one_off_lesson_id
       OR NEW.occurrence_date IS DISTINCT FROM OLD.occurrence_date
       OR NEW.assignment_id IS DISTINCT FROM OLD.assignment_id
       OR NEW.group_id IS DISTINCT FROM OLD.group_id
       OR NEW.subject_id IS DISTINCT FROM OLD.subject_id
       OR NEW.semester_id IS DISTINCT FROM OLD.semester_id
       OR NEW.assigned_teacher_id IS DISTINCT FROM OLD.assigned_teacher_id
       OR NEW.lesson_type IS DISTINCT FROM OLD.lesson_type
       OR NEW.generation < OLD.generation
       OR NEW.revision < OLD.revision THEN
        RAISE EXCEPTION 'lesson occurrence logical identity or ordering is immutable';
    END IF;
    RETURN NEW;
END
$$;

CREATE TRIGGER lesson_occurrences_identity_guard_trg
    BEFORE UPDATE ON lesson_occurrences
    FOR EACH ROW
    EXECUTE FUNCTION protect_occurrence_identity();

ALTER TABLE lesson_occurrences
    ADD CONSTRAINT lesson_occurrences_current_lesson_fk
        FOREIGN KEY (current_lesson_id, id)
        REFERENCES lessons (id, occurrence_id) ON DELETE RESTRICT
        DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE schedule_one_off_lessons
    ADD CONSTRAINT schedule_one_off_physical_lesson_fk
        FOREIGN KEY (physical_lesson_id)
        REFERENCES lessons (id) ON DELETE RESTRICT;

CREATE TABLE lesson_lifecycle_entries
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    occurrence_id     BIGINT      NOT NULL,
    revision          BIGINT      NOT NULL,
    action            VARCHAR(32) NOT NULL,
    lesson_id         BIGINT      NOT NULL,
    target_lesson_id  BIGINT,
    generation        BIGINT      NOT NULL,
    reason            VARCHAR(512),
    actor_id          BIGINT      NOT NULL,
    occurred_at       TIMESTAMPTZ NOT NULL,

    CONSTRAINT lesson_lifecycle_entries_id_positive_chk CHECK (id > 0),
    CONSTRAINT lesson_lifecycle_entries_occurrence_fk
        FOREIGN KEY (occurrence_id) REFERENCES lesson_occurrences (id) ON DELETE RESTRICT,
    CONSTRAINT lesson_lifecycle_entries_lesson_fk
        FOREIGN KEY (lesson_id, occurrence_id)
        REFERENCES lessons (id, occurrence_id) ON DELETE RESTRICT,
    CONSTRAINT lesson_lifecycle_entries_target_fk
        FOREIGN KEY (target_lesson_id, occurrence_id)
        REFERENCES lessons (id, occurrence_id) ON DELETE RESTRICT,
    CONSTRAINT lesson_lifecycle_entries_revision_chk CHECK (revision > 0),
    CONSTRAINT lesson_lifecycle_entries_generation_chk CHECK (generation > 0),
    CONSTRAINT lesson_lifecycle_entries_actor_chk CHECK (actor_id > 0),
    CONSTRAINT lesson_lifecycle_entries_action_chk
        CHECK (action IN ('CREATED', 'TRANSFERRED', 'CANCELLED', 'RESTORED', 'CLOSED')),
    CONSTRAINT lesson_lifecycle_entries_target_distinct_chk
        CHECK (target_lesson_id IS NULL OR target_lesson_id <> lesson_id),
    CONSTRAINT lesson_lifecycle_entries_revision_uq UNIQUE (occurrence_id, revision)
);

CREATE INDEX idx_lesson_lifecycle_entries_occurrence
    ON lesson_lifecycle_entries (occurrence_id, revision);

CREATE OR REPLACE FUNCTION reject_lesson_lifecycle_mutation()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    RAISE EXCEPTION 'lesson lifecycle entries are append-only';
END
$$;

CREATE TRIGGER lesson_lifecycle_entries_append_only_trg
    BEFORE UPDATE OR DELETE ON lesson_lifecycle_entries
    FOR EACH ROW
    EXECUTE FUNCTION reject_lesson_lifecycle_mutation();

CREATE TABLE schedule_transfer_replay
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_id            BIGINT      NOT NULL,
    request_key         UUID        NOT NULL,
    occurrence_id       BIGINT      NOT NULL,
    payload_hash        BYTEA       NOT NULL,
    source_lesson_id    BIGINT      NOT NULL,
    target_lesson_id    BIGINT      NOT NULL,
    accepted_revision   BIGINT      NOT NULL,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT schedule_transfer_replay_id_positive_chk CHECK (id > 0),
    CONSTRAINT schedule_transfer_replay_actor_chk CHECK (actor_id > 0),
    CONSTRAINT schedule_transfer_replay_occurrence_fk
        FOREIGN KEY (occurrence_id) REFERENCES lesson_occurrences (id) ON DELETE RESTRICT,
    CONSTRAINT schedule_transfer_replay_payload_hash_chk
        CHECK (octet_length(payload_hash) = 32),
    CONSTRAINT schedule_transfer_replay_source_fk
        FOREIGN KEY (source_lesson_id, occurrence_id)
        REFERENCES lessons (id, occurrence_id) ON DELETE RESTRICT,
    CONSTRAINT schedule_transfer_replay_target_fk
        FOREIGN KEY (target_lesson_id, occurrence_id)
        REFERENCES lessons (id, occurrence_id) ON DELETE RESTRICT,
    CONSTRAINT schedule_transfer_replay_source_target_chk
        CHECK (source_lesson_id <> target_lesson_id),
    CONSTRAINT schedule_transfer_replay_revision_chk CHECK (accepted_revision > 0),
    CONSTRAINT schedule_transfer_replay_actor_key_uq UNIQUE (actor_id, request_key)
);

CREATE OR REPLACE FUNCTION reject_schedule_transfer_replay_mutation()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    RAISE EXCEPTION 'schedule transfer replay is append-only';
END
$$;

CREATE TRIGGER schedule_transfer_replay_append_only_trg
    BEFORE UPDATE OR DELETE ON schedule_transfer_replay
    FOR EACH ROW
    EXECUTE FUNCTION reject_schedule_transfer_replay_mutation();

CREATE TABLE lesson_homework_bindings
(
    binding_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    occurrence_id     BIGINT      NOT NULL,
    current_lesson_id BIGINT      NOT NULL,
    homework_id       BIGINT,
    actor_id          BIGINT      NOT NULL,
    request_key       UUID        NOT NULL,
    payload_hash      BYTEA       NOT NULL,
    state             VARCHAR(16) NOT NULL,
    revision          BIGINT      NOT NULL DEFAULT 1,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at         TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT lesson_homework_bindings_id_positive_chk CHECK (binding_id > 0),
    CONSTRAINT lesson_homework_bindings_occurrence_fk
        FOREIGN KEY (occurrence_id) REFERENCES lesson_occurrences (id) ON DELETE RESTRICT,
    CONSTRAINT lesson_homework_bindings_current_lesson_fk
        FOREIGN KEY (current_lesson_id, occurrence_id)
        REFERENCES lessons (id, occurrence_id) ON DELETE RESTRICT,
    CONSTRAINT lesson_homework_bindings_homework_positive_chk
        CHECK (homework_id IS NULL OR homework_id > 0),
    CONSTRAINT lesson_homework_bindings_actor_chk CHECK (actor_id > 0),
    CONSTRAINT lesson_homework_bindings_payload_hash_chk
        CHECK (octet_length(payload_hash) = 32),
    CONSTRAINT lesson_homework_bindings_state_chk
        CHECK (state IN ('PENDING', 'ACTIVE', 'ARCHIVED')),
    CONSTRAINT lesson_homework_bindings_active_homework_chk
        CHECK (state <> 'ACTIVE' OR homework_id IS NOT NULL),
    CONSTRAINT lesson_homework_bindings_revision_chk CHECK (revision > 0),
    CONSTRAINT lesson_homework_bindings_actor_key_uq UNIQUE (actor_id, request_key)
);

CREATE UNIQUE INDEX uq_lesson_homework_bindings_homework
    ON lesson_homework_bindings (homework_id)
    WHERE homework_id IS NOT NULL;

CREATE INDEX idx_lesson_homework_bindings_homework
    ON lesson_homework_bindings (homework_id)
    WHERE homework_id IS NOT NULL;

CREATE OR REPLACE FUNCTION protect_lesson_homework_binding_identity()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'homework binding history is retained; archive the binding';
    END IF;
    IF NEW.binding_id IS DISTINCT FROM OLD.binding_id
       OR NEW.occurrence_id IS DISTINCT FROM OLD.occurrence_id
       OR NEW.actor_id IS DISTINCT FROM OLD.actor_id
       OR NEW.request_key IS DISTINCT FROM OLD.request_key
       OR NEW.payload_hash IS DISTINCT FROM OLD.payload_hash THEN
        RAISE EXCEPTION 'homework binding identity is immutable';
    END IF;
    IF OLD.homework_id IS NOT NULL
       AND NEW.homework_id IS DISTINCT FROM OLD.homework_id THEN
        RAISE EXCEPTION 'homework binding homework_id cannot be replaced';
    END IF;
    IF OLD.state = 'ARCHIVED' AND NEW.state <> 'ARCHIVED' THEN
        RAISE EXCEPTION 'archived homework binding cannot be reopened';
    END IF;
    IF NEW.revision < OLD.revision THEN
        RAISE EXCEPTION 'homework binding revision cannot move backwards';
    END IF;
    RETURN NEW;
END
$$;

CREATE TRIGGER lesson_homework_bindings_identity_guard_trg
    BEFORE UPDATE OR DELETE ON lesson_homework_bindings
    FOR EACH ROW
    EXECUTE FUNCTION protect_lesson_homework_binding_identity();
