-- Teacher replacement is the only workflow allowed to rebind an existing
-- recurring occurrence.  A fence keeps its retained-row boundary separate
-- from the boundary for creating new occurrences.

ALTER TABLE schedule_assignment_fences
    ADD COLUMN creation_cap_until_exclusive DATE;

UPDATE schedule_assignment_fences
   SET creation_cap_until_exclusive = cap_until_exclusive;

ALTER TABLE schedule_assignment_fences
    ALTER COLUMN creation_cap_until_exclusive SET NOT NULL,
    DROP CONSTRAINT schedule_assignment_fences_interval_chk,
    ADD CONSTRAINT schedule_assignment_fences_retention_interval_chk
        CHECK (cap_until_exclusive >= valid_from),
    ADD CONSTRAINT schedule_assignment_fences_creation_interval_chk
        CHECK (creation_cap_until_exclusive >= valid_from
               AND creation_cap_until_exclusive <= cap_until_exclusive);

CREATE TABLE schedule_assignment_replacement_operations
(
    operation_id         UUID PRIMARY KEY,
    payload_hash         BYTEA       NOT NULL,
    source_assignment_id BIGINT      NOT NULL,
    target_assignment_id BIGINT      NOT NULL,
    source_teacher_id    BIGINT      NOT NULL,
    target_teacher_id    BIGINT      NOT NULL,
    group_id             BIGINT      NOT NULL,
    subject_id           BIGINT      NOT NULL,
    semester_id          BIGINT      NOT NULL,
    lesson_type          VARCHAR(16) NOT NULL,
    source_valid_from    DATE        NOT NULL,
    valid_until_exclusive DATE       NOT NULL,
    effective_from       DATE        NOT NULL,
    state                VARCHAR(16) NOT NULL,
    moved_count          BIGINT      NOT NULL DEFAULT 0,
    skipped_count        BIGINT      NOT NULL DEFAULT 0,
    created_at           TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at           TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT schedule_assignment_replacement_hash_chk CHECK (octet_length(payload_hash) = 32),
    CONSTRAINT schedule_assignment_replacement_source_chk CHECK (source_assignment_id > 0),
    CONSTRAINT schedule_assignment_replacement_target_chk CHECK (target_assignment_id > 0),
    CONSTRAINT schedule_assignment_replacement_teachers_chk
        CHECK (source_teacher_id > 0 AND target_teacher_id > 0 AND source_teacher_id <> target_teacher_id),
    CONSTRAINT schedule_assignment_replacement_scope_chk
        CHECK (group_id > 0 AND subject_id > 0 AND semester_id > 0
               AND lesson_type IN ('lecture', 'practice', 'lab')),
    CONSTRAINT schedule_assignment_replacement_interval_chk
        CHECK (source_valid_from <= effective_from
               AND effective_from <= valid_until_exclusive
               AND valid_until_exclusive > effective_from),
    CONSTRAINT schedule_assignment_replacement_state_chk
        CHECK (state IN ('PREPARED', 'APPLIED', 'COMMITTED')),
    CONSTRAINT schedule_assignment_replacement_counts_chk
        CHECK (moved_count >= 0 AND skipped_count >= 0),
    CONSTRAINT schedule_assignment_replacement_pair_chk
        CHECK (source_assignment_id <> target_assignment_id)
);

CREATE TABLE schedule_assignment_replacement_templates
(
    operation_id              UUID   NOT NULL
        REFERENCES schedule_assignment_replacement_operations (operation_id) ON DELETE RESTRICT,
    source_schedule_item_id   BIGINT NOT NULL
        REFERENCES schedule_items (id) ON DELETE RESTRICT,
    target_schedule_item_id   BIGINT NOT NULL UNIQUE
        REFERENCES schedule_items (id) ON DELETE RESTRICT,
    source_was_active          BOOLEAN NOT NULL,
    created_at                TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    PRIMARY KEY (operation_id, source_schedule_item_id),
    CONSTRAINT schedule_assignment_replacement_template_distinct_chk
        CHECK (source_schedule_item_id <> target_schedule_item_id)
);

CREATE TABLE schedule_assignment_rebind_ledger
(
    ledger_id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    operation_id                 UUID        NOT NULL
        REFERENCES schedule_assignment_replacement_operations (operation_id) ON DELETE RESTRICT,
    source_schedule_item_id      BIGINT      NOT NULL
        REFERENCES schedule_items (id) ON DELETE RESTRICT,
    target_schedule_item_id      BIGINT      NOT NULL
        REFERENCES schedule_items (id) ON DELETE RESTRICT,
    occurrence_id                BIGINT      NOT NULL
        REFERENCES lesson_occurrences (id) ON DELETE RESTRICT,
    lesson_id                    BIGINT
        REFERENCES lessons (id) ON DELETE RESTRICT,
    occurrence_date              DATE        NOT NULL,
    expected_occurrence_revision BIGINT      NOT NULL,
    after_occurrence_revision    BIGINT      NOT NULL,
    expected_lesson_revision     BIGINT,
    after_lesson_revision        BIGINT,
    before_schedule_item_id      BIGINT      NOT NULL,
    after_schedule_item_id       BIGINT      NOT NULL,
    before_assignment_id         BIGINT      NOT NULL,
    after_assignment_id          BIGINT      NOT NULL,
    before_teacher_id            BIGINT      NOT NULL,
    after_teacher_id             BIGINT      NOT NULL,
    result                       VARCHAR(40) NOT NULL,
    created_at                   TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT schedule_assignment_rebind_revision_chk
        CHECK (expected_occurrence_revision > 0
               AND after_occurrence_revision >= expected_occurrence_revision
               AND (expected_lesson_revision IS NULL OR expected_lesson_revision > 0)
               AND (after_lesson_revision IS NULL OR after_lesson_revision >= expected_lesson_revision)),
    CONSTRAINT schedule_assignment_rebind_result_chk CHECK (result IN (
        'MOVED', 'SKIPPED_CANCELLED', 'SKIPPED_ACTIVE', 'SKIPPED_CLOSED',
        'SKIPPED_ALREADY_STARTED', 'SKIPPED_NO_CURRENT_LESSON')),
    CONSTRAINT schedule_assignment_rebind_date_uq
        UNIQUE (operation_id, source_schedule_item_id, occurrence_date)
);

CREATE INDEX idx_schedule_assignment_rebind_target_date
    ON schedule_assignment_rebind_ledger (after_assignment_id, occurrence_date);

CREATE OR REPLACE FUNCTION protect_schedule_assignment_fence()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    operation_id_value UUID;
    operation_source BIGINT;
    operation_target BIGINT;
    operation_date DATE;
    operation_state VARCHAR(16);
BEGIN
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'assignment fences are retained';
    END IF;

    IF NEW.assignment_id IS DISTINCT FROM OLD.assignment_id
       OR NEW.group_id IS DISTINCT FROM OLD.group_id
       OR NEW.subject_id IS DISTINCT FROM OLD.subject_id
       OR NEW.semester_id IS DISTINCT FROM OLD.semester_id
       OR NEW.assigned_teacher_id IS DISTINCT FROM OLD.assigned_teacher_id
       OR NEW.lesson_type IS DISTINCT FROM OLD.lesson_type
       OR NEW.valid_from IS DISTINCT FROM OLD.valid_from THEN
        RAISE EXCEPTION 'assignment fence provenance is immutable';
    END IF;
    IF NEW.revision < OLD.revision THEN
        RAISE EXCEPTION 'assignment fence revision cannot move backwards';
    END IF;

    IF NEW.cap_until_exclusive > OLD.cap_until_exclusive THEN
        RAISE EXCEPTION 'assignment retention cap cannot widen';
    END IF;
    IF NEW.cap_until_exclusive < OLD.cap_until_exclusive THEN
        IF EXISTS (SELECT 1 FROM lessons
                    WHERE assignment_id = OLD.assignment_id AND date >= NEW.cap_until_exclusive)
           OR EXISTS (SELECT 1 FROM lesson_occurrences
                       WHERE assignment_id = OLD.assignment_id
                         AND occurrence_date >= NEW.cap_until_exclusive) THEN
            RAISE EXCEPTION 'assignment retention cap cannot exclude retained rows';
        END IF;
    END IF;

    IF NEW.creation_cap_until_exclusive > OLD.creation_cap_until_exclusive THEN
        RAISE EXCEPTION 'assignment creation cap cannot widen';
    END IF;
    IF NEW.creation_cap_until_exclusive < OLD.creation_cap_until_exclusive THEN
        operation_id_value := NULLIF(current_setting(
            'rutcampustrack.schedule_assignment_rebind_operation_id', true), '')::UUID;
        IF operation_id_value IS NULL THEN
            RAISE EXCEPTION 'assignment creation cap can only narrow during replacement';
        END IF;
        SELECT source_assignment_id, target_assignment_id, effective_from, state
          INTO operation_source, operation_target, operation_date, operation_state
          FROM schedule_assignment_replacement_operations
         WHERE operation_id = operation_id_value
         FOR UPDATE;
        IF NOT FOUND OR operation_source <> OLD.assignment_id
           OR NEW.creation_cap_until_exclusive <> operation_date
           OR operation_state <> 'PREPARED' THEN
            RAISE EXCEPTION 'creation cap change does not match the exact prepared replacement';
        END IF;
    END IF;
    RETURN NEW;
END
$$;

CREATE OR REPLACE FUNCTION protect_schedule_assignment_replacement_operation()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'replacement operations are retained';
    END IF;
    IF NEW.operation_id IS DISTINCT FROM OLD.operation_id
       OR NEW.payload_hash IS DISTINCT FROM OLD.payload_hash
       OR NEW.source_assignment_id IS DISTINCT FROM OLD.source_assignment_id
       OR NEW.target_assignment_id IS DISTINCT FROM OLD.target_assignment_id
       OR NEW.source_teacher_id IS DISTINCT FROM OLD.source_teacher_id
       OR NEW.target_teacher_id IS DISTINCT FROM OLD.target_teacher_id
       OR NEW.group_id IS DISTINCT FROM OLD.group_id
       OR NEW.subject_id IS DISTINCT FROM OLD.subject_id
       OR NEW.semester_id IS DISTINCT FROM OLD.semester_id
       OR NEW.lesson_type IS DISTINCT FROM OLD.lesson_type
       OR NEW.source_valid_from IS DISTINCT FROM OLD.source_valid_from
       OR NEW.valid_until_exclusive IS DISTINCT FROM OLD.valid_until_exclusive
       OR NEW.effective_from IS DISTINCT FROM OLD.effective_from
       OR NEW.created_at IS DISTINCT FROM OLD.created_at THEN
        RAISE EXCEPTION 'replacement operation identity is immutable';
    END IF;
    IF NOT ((OLD.state = 'PREPARED' AND NEW.state = 'APPLIED')
         OR (OLD.state = 'APPLIED' AND NEW.state = 'COMMITTED')
         OR (OLD.state = NEW.state)) THEN
        RAISE EXCEPTION 'invalid replacement operation transition';
    END IF;
    IF NEW.moved_count < OLD.moved_count OR NEW.skipped_count < OLD.skipped_count THEN
        RAISE EXCEPTION 'replacement operation receipt cannot move backwards';
    END IF;
    RETURN NEW;
END
$$;

CREATE TRIGGER schedule_assignment_replacement_operation_guard_trg
    BEFORE UPDATE OR DELETE ON schedule_assignment_replacement_operations
    FOR EACH ROW EXECUTE FUNCTION protect_schedule_assignment_replacement_operation();

CREATE OR REPLACE FUNCTION reject_schedule_assignment_replacement_template_mutation()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    RAISE EXCEPTION 'replacement template mappings are append-only';
END
$$;

CREATE TRIGGER schedule_assignment_replacement_templates_append_only_trg
    BEFORE UPDATE OR DELETE ON schedule_assignment_replacement_templates
    FOR EACH ROW EXECUTE FUNCTION reject_schedule_assignment_replacement_template_mutation();

CREATE OR REPLACE FUNCTION validate_schedule_assignment_replacement_template_insert()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    operation_state_value VARCHAR(16);
    source_active_value BOOLEAN;
    target_active_value BOOLEAN;
BEGIN
    SELECT state INTO operation_state_value
      FROM schedule_assignment_replacement_operations
     WHERE operation_id = NEW.operation_id
     FOR UPDATE;
    IF NOT FOUND OR operation_state_value <> 'APPLIED' THEN
        RAISE EXCEPTION 'replacement templates are cloned only during the confirmed apply phase';
    END IF;
    SELECT is_active INTO source_active_value
      FROM schedule_items
     WHERE id = NEW.source_schedule_item_id
     FOR UPDATE;
    IF NOT FOUND OR source_active_value IS DISTINCT FROM NEW.source_was_active THEN
        RAISE EXCEPTION 'replacement template active state differs from its source';
    END IF;
    SELECT is_active INTO target_active_value
      FROM schedule_items
     WHERE id = NEW.target_schedule_item_id
     FOR UPDATE;
    IF NOT FOUND OR target_active_value THEN
        RAISE EXCEPTION 'replacement target template must remain inactive until commit';
    END IF;
    RETURN NEW;
END
$$;

CREATE TRIGGER schedule_assignment_replacement_templates_validate_trg
    BEFORE INSERT ON schedule_assignment_replacement_templates
    FOR EACH ROW EXECUTE FUNCTION validate_schedule_assignment_replacement_template_insert();

CREATE OR REPLACE FUNCTION guard_pending_replacement_assignment_insert()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    operation_id_value UUID;
BEGIN
    operation_id_value := NULLIF(current_setting(
        'rutcampustrack.schedule_assignment_rebind_operation_id', true), '')::UUID;
    IF EXISTS (
        SELECT 1
          FROM schedule_assignment_replacement_operations
         WHERE target_assignment_id = NEW.assignment_id
           AND state <> 'COMMITTED'
           AND (operation_id IS DISTINCT FROM operation_id_value OR state <> 'APPLIED')
    ) THEN
        RAISE EXCEPTION 'target assignment is fenced until replacement schedule commit';
    END IF;
    RETURN NEW;
END
$$;

CREATE TRIGGER schedule_items_pending_replacement_insert_trg
    BEFORE INSERT ON schedule_items
    FOR EACH ROW EXECUTE FUNCTION guard_pending_replacement_assignment_insert();

CREATE TRIGGER lesson_occurrences_pending_replacement_insert_trg
    BEFORE INSERT ON lesson_occurrences
    FOR EACH ROW EXECUTE FUNCTION guard_pending_replacement_assignment_insert();

CREATE TRIGGER lessons_pending_replacement_insert_trg
    BEFORE INSERT ON lessons
    FOR EACH ROW EXECUTE FUNCTION guard_pending_replacement_assignment_insert();

CREATE OR REPLACE FUNCTION validate_schedule_assignment_rebind_ledger_insert()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    operation_row schedule_assignment_replacement_operations%ROWTYPE;
    occurrence_row lesson_occurrences%ROWTYPE;
    lesson_row lessons%ROWTYPE;
BEGIN
    SELECT * INTO operation_row
      FROM schedule_assignment_replacement_operations
     WHERE operation_id = NEW.operation_id
     FOR UPDATE;
    IF NOT FOUND OR operation_row.state <> 'APPLIED'
       OR NEW.occurrence_date < operation_row.effective_from
       OR NEW.occurrence_date >= operation_row.valid_until_exclusive
       OR NEW.before_assignment_id <> operation_row.source_assignment_id
       OR NEW.after_assignment_id NOT IN (operation_row.source_assignment_id,
                                           operation_row.target_assignment_id)
       OR NEW.before_teacher_id <> operation_row.source_teacher_id
       OR NEW.after_teacher_id NOT IN (operation_row.source_teacher_id,
                                       operation_row.target_teacher_id)
       OR NEW.before_schedule_item_id <> NEW.source_schedule_item_id
       OR NEW.after_schedule_item_id NOT IN (NEW.source_schedule_item_id,
                                              NEW.target_schedule_item_id) THEN
        RAISE EXCEPTION 'replacement ledger entry does not match its operation';
    END IF;
    IF NOT EXISTS (SELECT 1 FROM schedule_assignment_replacement_templates
                    WHERE operation_id = NEW.operation_id
                      AND source_schedule_item_id = NEW.source_schedule_item_id
                      AND target_schedule_item_id = NEW.target_schedule_item_id) THEN
        RAISE EXCEPTION 'replacement ledger entry has no exact template mapping';
    END IF;
    IF NOT EXISTS (
        SELECT 1
          FROM schedule_items source_item
          JOIN schedule_items target_item ON target_item.id = NEW.target_schedule_item_id
         WHERE source_item.id = NEW.source_schedule_item_id
           AND source_item.assignment_id = operation_row.source_assignment_id
           AND source_item.group_id = operation_row.group_id
           AND source_item.subject_id = operation_row.subject_id
           AND source_item.semester_id = operation_row.semester_id
           AND target_item.assignment_id = operation_row.target_assignment_id
           AND target_item.group_id = operation_row.group_id
           AND target_item.subject_id = operation_row.subject_id
           AND target_item.semester_id = operation_row.semester_id
           AND target_item.day_of_week = source_item.day_of_week
           AND target_item.lesson_number = source_item.lesson_number
           AND target_item.start_time = source_item.start_time
           AND target_item.end_time = source_item.end_time
           AND target_item.week_type = source_item.week_type
           AND target_item.room IS NOT DISTINCT FROM source_item.room
    ) THEN
        RAISE EXCEPTION 'replacement template does not preserve its recurring schedule tuple';
    END IF;

    SELECT * INTO occurrence_row FROM lesson_occurrences
     WHERE id = NEW.occurrence_id FOR UPDATE;
    IF NOT FOUND OR occurrence_row.schedule_item_id <> NEW.source_schedule_item_id
       OR occurrence_row.assignment_id <> operation_row.source_assignment_id
       OR occurrence_row.assigned_teacher_id <> operation_row.source_teacher_id
       OR occurrence_row.group_id <> operation_row.group_id
       OR occurrence_row.subject_id <> operation_row.subject_id
       OR occurrence_row.semester_id <> operation_row.semester_id
       OR occurrence_row.lesson_type <> operation_row.lesson_type
       OR occurrence_row.occurrence_date <> NEW.occurrence_date
       OR occurrence_row.revision <> NEW.expected_occurrence_revision
       OR occurrence_row.current_lesson_id IS DISTINCT FROM NEW.lesson_id THEN
        RAISE EXCEPTION 'replacement ledger entry does not match current occurrence revision';
    END IF;

    IF NEW.result = 'MOVED' THEN
        IF NEW.lesson_id IS NULL OR NEW.expected_lesson_revision IS NULL
           OR NEW.after_schedule_item_id <> NEW.target_schedule_item_id
           OR NEW.after_assignment_id <> operation_row.target_assignment_id
           OR NEW.after_teacher_id <> operation_row.target_teacher_id
           OR NEW.after_occurrence_revision <> NEW.expected_occurrence_revision + 1
           OR NEW.after_lesson_revision <> NEW.expected_lesson_revision + 1 THEN
            RAISE EXCEPTION 'moved replacement ledger entry is incomplete';
        END IF;
        SELECT * INTO lesson_row FROM lessons WHERE id = NEW.lesson_id FOR UPDATE;
        IF NOT FOUND OR lesson_row.status::text <> 'planned'
           OR lesson_row.occurrence_id <> NEW.occurrence_id
           OR lesson_row.schedule_item_id <> NEW.source_schedule_item_id
           OR lesson_row.assignment_id <> operation_row.source_assignment_id
           OR lesson_row.assigned_teacher_id <> operation_row.source_teacher_id
           OR lesson_row.group_id <> operation_row.group_id
           OR lesson_row.subject_id <> operation_row.subject_id
           OR lesson_row.semester_id <> operation_row.semester_id
           OR lesson_row.lesson_type <> operation_row.lesson_type
           OR lesson_row.date <> NEW.occurrence_date
           OR lesson_row.revision <> NEW.expected_lesson_revision THEN
            RAISE EXCEPTION 'only the exact current planned lesson can be rebound';
        END IF;
    ELSE
        IF NEW.after_schedule_item_id <> NEW.source_schedule_item_id
           OR NEW.after_assignment_id <> operation_row.source_assignment_id
           OR NEW.after_teacher_id <> operation_row.source_teacher_id
           OR NEW.after_occurrence_revision <> NEW.expected_occurrence_revision
           OR NEW.after_lesson_revision IS DISTINCT FROM NEW.expected_lesson_revision THEN
            RAISE EXCEPTION 'skipped replacement rows must retain source snapshots';
        END IF;
        IF NEW.lesson_id IS NULL THEN
            IF NEW.result <> 'SKIPPED_NO_CURRENT_LESSON'
               OR NEW.expected_lesson_revision IS NOT NULL THEN
                RAISE EXCEPTION 'missing current lesson must have an explicit skip disposition';
            END IF;
        ELSE
            SELECT * INTO lesson_row FROM lessons WHERE id = NEW.lesson_id FOR UPDATE;
            IF NOT FOUND OR lesson_row.occurrence_id <> NEW.occurrence_id
               OR lesson_row.status::text = 'planned'
               OR lesson_row.revision <> NEW.expected_lesson_revision THEN
                RAISE EXCEPTION 'skipped replacement entry does not match held lesson';
            END IF;
            IF (lesson_row.status::text = 'cancelled' AND NEW.result <> 'SKIPPED_CANCELLED')
               OR (lesson_row.status::text = 'active' AND NEW.result <> 'SKIPPED_ACTIVE')
               OR (lesson_row.status::text = 'closed' AND NEW.result <> 'SKIPPED_CLOSED')
               OR (lesson_row.status::text NOT IN ('cancelled', 'active', 'closed')
                   AND NEW.result <> 'SKIPPED_ALREADY_STARTED') THEN
                RAISE EXCEPTION 'skip disposition does not match current lesson status';
            END IF;
        END IF;
    END IF;
    RETURN NEW;
END
$$;

CREATE TRIGGER schedule_assignment_rebind_ledger_validate_trg
    BEFORE INSERT ON schedule_assignment_rebind_ledger
    FOR EACH ROW EXECUTE FUNCTION validate_schedule_assignment_rebind_ledger_insert();

CREATE OR REPLACE FUNCTION reject_schedule_assignment_rebind_ledger_mutation()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    RAISE EXCEPTION 'replacement rebind ledger is append-only';
END
$$;

CREATE TRIGGER schedule_assignment_rebind_ledger_append_only_trg
    BEFORE UPDATE OR DELETE ON schedule_assignment_rebind_ledger
    FOR EACH ROW EXECUTE FUNCTION reject_schedule_assignment_rebind_ledger_mutation();

CREATE OR REPLACE FUNCTION protect_occurrence_identity()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    operation_id_value UUID;
    operation_row schedule_assignment_replacement_operations%ROWTYPE;
    ledger_row schedule_assignment_rebind_ledger%ROWTYPE;
BEGIN
    IF NEW.one_off_lesson_id IS DISTINCT FROM OLD.one_off_lesson_id
       OR NEW.occurrence_date IS DISTINCT FROM OLD.occurrence_date
       OR NEW.group_id IS DISTINCT FROM OLD.group_id
       OR NEW.subject_id IS DISTINCT FROM OLD.subject_id
       OR NEW.semester_id IS DISTINCT FROM OLD.semester_id
       OR NEW.lesson_type IS DISTINCT FROM OLD.lesson_type
       OR NEW.generation < OLD.generation
       OR NEW.revision < OLD.revision THEN
        RAISE EXCEPTION 'lesson occurrence identity, current pointer, or ordering is immutable';
    END IF;

    IF NEW.schedule_item_id IS DISTINCT FROM OLD.schedule_item_id
       OR NEW.assignment_id IS DISTINCT FROM OLD.assignment_id
       OR NEW.assigned_teacher_id IS DISTINCT FROM OLD.assigned_teacher_id THEN
        operation_id_value := NULLIF(current_setting(
            'rutcampustrack.schedule_assignment_rebind_operation_id', true), '')::UUID;
        IF operation_id_value IS NULL THEN
            RAISE EXCEPTION 'occurrence provenance changes require an exact replacement ledger row';
        END IF;
        SELECT * INTO operation_row
          FROM schedule_assignment_replacement_operations
         WHERE operation_id = operation_id_value FOR UPDATE;
        SELECT * INTO ledger_row
          FROM schedule_assignment_rebind_ledger
         WHERE operation_id = operation_id_value
           AND occurrence_id = OLD.id
           AND result = 'MOVED' FOR UPDATE;
        IF NOT FOUND OR operation_row.state <> 'APPLIED'
           OR NEW.current_lesson_id IS DISTINCT FROM OLD.current_lesson_id
           OR OLD.assignment_id <> operation_row.source_assignment_id
           OR NEW.assignment_id <> operation_row.target_assignment_id
           OR OLD.assigned_teacher_id <> operation_row.source_teacher_id
           OR NEW.assigned_teacher_id <> operation_row.target_teacher_id
           OR NEW.schedule_item_id <> ledger_row.target_schedule_item_id
           OR OLD.schedule_item_id <> ledger_row.source_schedule_item_id
           OR OLD.occurrence_date < operation_row.effective_from
           OR ledger_row.occurrence_date <> OLD.occurrence_date
           OR ledger_row.expected_occurrence_revision <> OLD.revision
           OR NEW.revision <> OLD.revision + 1
           OR ledger_row.after_occurrence_revision <> NEW.revision
           OR ledger_row.before_assignment_id <> OLD.assignment_id
           OR ledger_row.after_assignment_id <> NEW.assignment_id
           OR ledger_row.before_teacher_id <> OLD.assigned_teacher_id
           OR ledger_row.after_teacher_id <> NEW.assigned_teacher_id THEN
            RAISE EXCEPTION 'occurrence update is outside the exact replacement ledger entry';
        END IF;
    END IF;
    RETURN NEW;
END
$$;

CREATE OR REPLACE FUNCTION validate_recurring_occurrence_fence()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    fence_record schedule_assignment_fences%ROWTYPE;
    schedule_item_record schedule_items%ROWTYPE;
BEGIN
    SELECT * INTO fence_record FROM schedule_assignment_fences
     WHERE assignment_id = NEW.assignment_id FOR UPDATE;
    IF NOT FOUND THEN RAISE EXCEPTION 'assignment fence % does not exist', NEW.assignment_id; END IF;
    IF NEW.schedule_item_id IS NULL THEN RAISE EXCEPTION 'recurring occurrence requires a schedule item'; END IF;
    SELECT * INTO schedule_item_record FROM schedule_items
     WHERE id = NEW.schedule_item_id FOR UPDATE;
    IF NOT FOUND THEN RAISE EXCEPTION 'schedule item % does not exist', NEW.schedule_item_id; END IF;
    IF schedule_item_record.assignment_id IS DISTINCT FROM fence_record.assignment_id
       OR schedule_item_record.group_id IS DISTINCT FROM fence_record.group_id
       OR schedule_item_record.subject_id IS DISTINCT FROM fence_record.subject_id
       OR schedule_item_record.semester_id IS DISTINCT FROM fence_record.semester_id
       OR NEW.assignment_id IS DISTINCT FROM fence_record.assignment_id
       OR NEW.group_id IS DISTINCT FROM fence_record.group_id
       OR NEW.subject_id IS DISTINCT FROM fence_record.subject_id
       OR NEW.semester_id IS DISTINCT FROM fence_record.semester_id
       OR NEW.assigned_teacher_id IS DISTINCT FROM fence_record.assigned_teacher_id
       OR NEW.lesson_type IS DISTINCT FROM fence_record.lesson_type
       OR NEW.occurrence_date < fence_record.valid_from
       OR NEW.occurrence_date >= fence_record.creation_cap_until_exclusive THEN
        RAISE EXCEPTION 'recurring occurrence violates assignment creation fence %', NEW.assignment_id;
    END IF;
    RETURN NEW;
END
$$;

CREATE OR REPLACE FUNCTION validate_lesson_insert_fence()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    fence_record schedule_assignment_fences%ROWTYPE;
BEGIN
    IF NEW.day_of_week IS NULL OR NEW.week_type_snapshot IS NULL THEN
        RAISE EXCEPTION 'new physical lessons require immutable schedule snapshots';
    END IF;
    SELECT * INTO fence_record FROM schedule_assignment_fences
     WHERE assignment_id = NEW.assignment_id FOR UPDATE;
    IF NOT FOUND THEN RAISE EXCEPTION 'assignment fence % does not exist', NEW.assignment_id; END IF;
    IF NEW.assignment_id IS DISTINCT FROM fence_record.assignment_id
       OR NEW.group_id IS DISTINCT FROM fence_record.group_id
       OR NEW.subject_id IS DISTINCT FROM fence_record.subject_id
       OR NEW.semester_id IS DISTINCT FROM fence_record.semester_id
       OR NEW.assigned_teacher_id IS DISTINCT FROM fence_record.assigned_teacher_id
       OR NEW.lesson_type IS DISTINCT FROM fence_record.lesson_type
       OR NEW.date < fence_record.valid_from
       OR NEW.date >= fence_record.creation_cap_until_exclusive THEN
        RAISE EXCEPTION 'physical lesson identity snapshot violates its creation fence';
    END IF;
    RETURN NEW;
END
$$;

CREATE OR REPLACE FUNCTION validate_lesson_physical_snapshot()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    occurrence_record lesson_occurrences%ROWTYPE;
    operation_id_value UUID;
    operation_row schedule_assignment_replacement_operations%ROWTYPE;
    ledger_row schedule_assignment_rebind_ledger%ROWTYPE;
    identity_changed BOOLEAN;
BEGIN
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'physical lessons are retained; use a lifecycle state';
    END IF;
    SELECT * INTO occurrence_record FROM lesson_occurrences WHERE id = NEW.occurrence_id;
    IF NOT FOUND THEN RAISE EXCEPTION 'lesson occurrence % does not exist', NEW.occurrence_id; END IF;

    identity_changed := TG_OP = 'UPDATE' AND (
        NEW.schedule_item_id IS DISTINCT FROM OLD.schedule_item_id
        OR NEW.assignment_id IS DISTINCT FROM OLD.assignment_id
        OR NEW.assigned_teacher_id IS DISTINCT FROM OLD.assigned_teacher_id);
    IF identity_changed THEN
        operation_id_value := NULLIF(current_setting(
            'rutcampustrack.schedule_assignment_rebind_operation_id', true), '')::UUID;
        IF operation_id_value IS NULL THEN
            RAISE EXCEPTION 'physical lesson provenance changes require an exact replacement ledger row';
        END IF;
        SELECT * INTO operation_row FROM schedule_assignment_replacement_operations
         WHERE operation_id = operation_id_value FOR UPDATE;
        SELECT * INTO ledger_row FROM schedule_assignment_rebind_ledger
         WHERE operation_id = operation_id_value AND occurrence_id = OLD.occurrence_id
           AND lesson_id = OLD.id AND result = 'MOVED' FOR UPDATE;
        IF NOT FOUND OR operation_row.state <> 'APPLIED'
           OR OLD.status::text <> 'planned' OR NEW.status IS DISTINCT FROM OLD.status
           OR OLD.date < operation_row.effective_from
           OR OLD.schedule_item_id <> ledger_row.source_schedule_item_id
           OR NEW.schedule_item_id <> ledger_row.target_schedule_item_id
           OR OLD.assignment_id <> operation_row.source_assignment_id
           OR NEW.assignment_id <> operation_row.target_assignment_id
           OR OLD.assigned_teacher_id <> operation_row.source_teacher_id
           OR NEW.assigned_teacher_id <> operation_row.target_teacher_id
           OR OLD.revision <> ledger_row.expected_lesson_revision
           OR NEW.revision <> OLD.revision + 1
           OR ledger_row.after_lesson_revision <> NEW.revision THEN
            RAISE EXCEPTION 'physical lesson update is outside the exact replacement ledger entry';
        END IF;
    END IF;

    IF NEW.occurrence_id IS DISTINCT FROM occurrence_record.id
       OR NEW.schedule_item_id IS DISTINCT FROM occurrence_record.schedule_item_id
       OR NEW.one_off_lesson_id IS DISTINCT FROM occurrence_record.one_off_lesson_id
       OR NEW.assignment_id IS DISTINCT FROM occurrence_record.assignment_id
       OR NEW.group_id IS DISTINCT FROM occurrence_record.group_id
       OR NEW.subject_id IS DISTINCT FROM occurrence_record.subject_id
       OR NEW.semester_id IS DISTINCT FROM occurrence_record.semester_id
       OR NEW.assigned_teacher_id IS DISTINCT FROM occurrence_record.assigned_teacher_id
       OR NEW.lesson_type IS DISTINCT FROM occurrence_record.lesson_type THEN
        RAISE EXCEPTION 'physical lesson identity snapshot does not match its occurrence';
    END IF;
    IF TG_OP = 'UPDATE'
       AND (NEW.id IS DISTINCT FROM OLD.id
            OR NEW.schedule_item_id IS DISTINCT FROM OLD.schedule_item_id AND NOT identity_changed
            OR NEW.one_off_lesson_id IS DISTINCT FROM OLD.one_off_lesson_id
            OR NEW.occurrence_id IS DISTINCT FROM OLD.occurrence_id
            OR NEW.assignment_id IS DISTINCT FROM OLD.assignment_id AND NOT identity_changed
            OR NEW.group_id IS DISTINCT FROM OLD.group_id
            OR NEW.subject_id IS DISTINCT FROM OLD.subject_id
            OR NEW.semester_id IS DISTINCT FROM OLD.semester_id
            OR NEW.assigned_teacher_id IS DISTINCT FROM OLD.assigned_teacher_id AND NOT identity_changed
            OR NEW.lesson_type IS DISTINCT FROM OLD.lesson_type
            OR NEW.date IS DISTINCT FROM OLD.date
            OR NEW.lesson_number IS DISTINCT FROM OLD.lesson_number
            OR NEW.day_of_week IS DISTINCT FROM OLD.day_of_week
            OR NEW.start_time IS DISTINCT FROM OLD.start_time
            OR NEW.end_time IS DISTINCT FROM OLD.end_time
            OR NEW.room_snapshot IS DISTINCT FROM OLD.room_snapshot
            OR NEW.week_type_snapshot IS DISTINCT FROM OLD.week_type_snapshot
            OR NEW.generation IS DISTINCT FROM OLD.generation) THEN
        RAISE EXCEPTION 'physical lesson identity snapshot is immutable';
    END IF;
    IF TG_OP = 'UPDATE' AND NEW.revision < OLD.revision THEN
        RAISE EXCEPTION 'physical lesson revision cannot move backwards';
    END IF;
    RETURN NEW;
END
$$;
