# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import academic_pb2 as academic__pb2

GRPC_GENERATED_VERSION = '1.73.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in academic_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AcademicGrpcServiceStub(object):
    """Academic Structure Service — gRPC контракт
    Используется другими сервисами для получения справочных данных

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetGroup = channel.unary_unary(
                '/rutcampustrack.academic.AcademicGrpcService/GetGroup',
                request_serializer=academic__pb2.GroupRequest.SerializeToString,
                response_deserializer=academic__pb2.GroupResponse.FromString,
                _registered_method=True)
        self.GetGroupMembers = channel.unary_unary(
                '/rutcampustrack.academic.AcademicGrpcService/GetGroupMembers',
                request_serializer=academic__pb2.GroupMembersRequest.SerializeToString,
                response_deserializer=academic__pb2.GroupMembersResponse.FromString,
                _registered_method=True)
        self.GetTeacherSubjects = channel.unary_unary(
                '/rutcampustrack.academic.AcademicGrpcService/GetTeacherSubjects',
                request_serializer=academic__pb2.TeacherSubjectsRequest.SerializeToString,
                response_deserializer=academic__pb2.TeacherSubjectsResponse.FromString,
                _registered_method=True)
        self.IsHeadman = channel.unary_unary(
                '/rutcampustrack.academic.AcademicGrpcService/IsHeadman',
                request_serializer=academic__pb2.HeadmanCheckRequest.SerializeToString,
                response_deserializer=academic__pb2.HeadmanCheckResponse.FromString,
                _registered_method=True)
        self.GetActiveSemester = channel.unary_unary(
                '/rutcampustrack.academic.AcademicGrpcService/GetActiveSemester',
                request_serializer=academic__pb2.Empty.SerializeToString,
                response_deserializer=academic__pb2.SemesterResponse.FromString,
                _registered_method=True)
        self.GetCampusGeofence = channel.unary_unary(
                '/rutcampustrack.academic.AcademicGrpcService/GetCampusGeofence',
                request_serializer=academic__pb2.Empty.SerializeToString,
                response_deserializer=academic__pb2.GeofenceResponse.FromString,
                _registered_method=True)
        self.GetUserById = channel.unary_unary(
                '/rutcampustrack.academic.AcademicGrpcService/GetUserById',
                request_serializer=academic__pb2.UserRequest.SerializeToString,
                response_deserializer=academic__pb2.UserResponse.FromString,
                _registered_method=True)
        self.GetSubjectsByIds = channel.unary_unary(
                '/rutcampustrack.academic.AcademicGrpcService/GetSubjectsByIds',
                request_serializer=academic__pb2.SubjectsByIdsRequest.SerializeToString,
                response_deserializer=academic__pb2.SubjectsByIdsResponse.FromString,
                _registered_method=True)


class AcademicGrpcServiceServicer(object):
    """Academic Structure Service — gRPC контракт
    Используется другими сервисами для получения справочных данных

    """

    def GetGroup(self, request, context):
        """Получить информацию о группе
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetGroupMembers(self, request, context):
        """Получить состав группы (список студентов)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTeacherSubjects(self, request, context):
        """Получить предметы преподавателя (для авторизации в Report)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IsHeadman(self, request, context):
        """Проверить, является ли пользователь старостой группы
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetActiveSemester(self, request, context):
        """Получить активный семестр
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCampusGeofence(self, request, context):
        """Получить геофенс кампуса
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserById(self, request, context):
        """Получить пользователя по ID
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSubjectsByIds(self, request, context):
        """Получить предметы по списку ID (для отчётов посещаемости)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AcademicGrpcServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetGroup': grpc.unary_unary_rpc_method_handler(
                    servicer.GetGroup,
                    request_deserializer=academic__pb2.GroupRequest.FromString,
                    response_serializer=academic__pb2.GroupResponse.SerializeToString,
            ),
            'GetGroupMembers': grpc.unary_unary_rpc_method_handler(
                    servicer.GetGroupMembers,
                    request_deserializer=academic__pb2.GroupMembersRequest.FromString,
                    response_serializer=academic__pb2.GroupMembersResponse.SerializeToString,
            ),
            'GetTeacherSubjects': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTeacherSubjects,
                    request_deserializer=academic__pb2.TeacherSubjectsRequest.FromString,
                    response_serializer=academic__pb2.TeacherSubjectsResponse.SerializeToString,
            ),
            'IsHeadman': grpc.unary_unary_rpc_method_handler(
                    servicer.IsHeadman,
                    request_deserializer=academic__pb2.HeadmanCheckRequest.FromString,
                    response_serializer=academic__pb2.HeadmanCheckResponse.SerializeToString,
            ),
            'GetActiveSemester': grpc.unary_unary_rpc_method_handler(
                    servicer.GetActiveSemester,
                    request_deserializer=academic__pb2.Empty.FromString,
                    response_serializer=academic__pb2.SemesterResponse.SerializeToString,
            ),
            'GetCampusGeofence': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCampusGeofence,
                    request_deserializer=academic__pb2.Empty.FromString,
                    response_serializer=academic__pb2.GeofenceResponse.SerializeToString,
            ),
            'GetUserById': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserById,
                    request_deserializer=academic__pb2.UserRequest.FromString,
                    response_serializer=academic__pb2.UserResponse.SerializeToString,
            ),
            'GetSubjectsByIds': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSubjectsByIds,
                    request_deserializer=academic__pb2.SubjectsByIdsRequest.FromString,
                    response_serializer=academic__pb2.SubjectsByIdsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'rutcampustrack.academic.AcademicGrpcService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('rutcampustrack.academic.AcademicGrpcService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AcademicGrpcService(object):
    """Academic Structure Service — gRPC контракт
    Используется другими сервисами для получения справочных данных

    """

    @staticmethod
    def GetGroup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rutcampustrack.academic.AcademicGrpcService/GetGroup',
            academic__pb2.GroupRequest.SerializeToString,
            academic__pb2.GroupResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetGroupMembers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rutcampustrack.academic.AcademicGrpcService/GetGroupMembers',
            academic__pb2.GroupMembersRequest.SerializeToString,
            academic__pb2.GroupMembersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTeacherSubjects(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rutcampustrack.academic.AcademicGrpcService/GetTeacherSubjects',
            academic__pb2.TeacherSubjectsRequest.SerializeToString,
            academic__pb2.TeacherSubjectsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IsHeadman(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rutcampustrack.academic.AcademicGrpcService/IsHeadman',
            academic__pb2.HeadmanCheckRequest.SerializeToString,
            academic__pb2.HeadmanCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetActiveSemester(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rutcampustrack.academic.AcademicGrpcService/GetActiveSemester',
            academic__pb2.Empty.SerializeToString,
            academic__pb2.SemesterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCampusGeofence(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rutcampustrack.academic.AcademicGrpcService/GetCampusGeofence',
            academic__pb2.Empty.SerializeToString,
            academic__pb2.GeofenceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUserById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rutcampustrack.academic.AcademicGrpcService/GetUserById',
            academic__pb2.UserRequest.SerializeToString,
            academic__pb2.UserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSubjectsByIds(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rutcampustrack.academic.AcademicGrpcService/GetSubjectsByIds',
            academic__pb2.SubjectsByIdsRequest.SerializeToString,
            academic__pb2.SubjectsByIdsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
