# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from bot.grpc_client import schedule_pb2 as schedule__pb2

GRPC_GENERATED_VERSION = '1.73.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in schedule_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ScheduleGrpcServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetActiveLesson = channel.unary_unary(
                '/rutcampustrack.schedule.ScheduleGrpcService/GetActiveLesson',
                request_serializer=schedule__pb2.ActiveLessonRequest.SerializeToString,
                response_deserializer=schedule__pb2.LessonResponse.FromString,
                _registered_method=True)
        self.GetLessonById = channel.unary_unary(
                '/rutcampustrack.schedule.ScheduleGrpcService/GetLessonById',
                request_serializer=schedule__pb2.LessonByIdRequest.SerializeToString,
                response_deserializer=schedule__pb2.LessonResponse.FromString,
                _registered_method=True)
        self.GetLessonsByGroup = channel.unary_unary(
                '/rutcampustrack.schedule.ScheduleGrpcService/GetLessonsByGroup',
                request_serializer=schedule__pb2.LessonsByGroupRequest.SerializeToString,
                response_deserializer=schedule__pb2.LessonsResponse.FromString,
                _registered_method=True)


class ScheduleGrpcServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetActiveLesson(self, request, context):
        """Получить активную пару для группы в данный момент
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLessonById(self, request, context):
        """Получить пару по ID
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLessonsByGroup(self, request, context):
        """Получить все пары группы за период
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ScheduleGrpcServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetActiveLesson': grpc.unary_unary_rpc_method_handler(
                    servicer.GetActiveLesson,
                    request_deserializer=schedule__pb2.ActiveLessonRequest.FromString,
                    response_serializer=schedule__pb2.LessonResponse.SerializeToString,
            ),
            'GetLessonById': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLessonById,
                    request_deserializer=schedule__pb2.LessonByIdRequest.FromString,
                    response_serializer=schedule__pb2.LessonResponse.SerializeToString,
            ),
            'GetLessonsByGroup': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLessonsByGroup,
                    request_deserializer=schedule__pb2.LessonsByGroupRequest.FromString,
                    response_serializer=schedule__pb2.LessonsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'rutcampustrack.schedule.ScheduleGrpcService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('rutcampustrack.schedule.ScheduleGrpcService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ScheduleGrpcService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetActiveLesson(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rutcampustrack.schedule.ScheduleGrpcService/GetActiveLesson',
            schedule__pb2.ActiveLessonRequest.SerializeToString,
            schedule__pb2.LessonResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetLessonById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rutcampustrack.schedule.ScheduleGrpcService/GetLessonById',
            schedule__pb2.LessonByIdRequest.SerializeToString,
            schedule__pb2.LessonResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetLessonsByGroup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rutcampustrack.schedule.ScheduleGrpcService/GetLessonsByGroup',
            schedule__pb2.LessonsByGroupRequest.SerializeToString,
            schedule__pb2.LessonsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
