# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: schedule.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(_runtime_version.Domain.PUBLIC, 6, 31, 0, "", "schedule.proto")
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0eschedule.proto\x12\x17rutcampustrack.schedule":\n\x13\x41\x63tiveLessonRequest\x12\x10\n\x08group_id\x18\x01 \x01(\x03\x12\x11\n\ttimestamp\x18\x02 \x01(\t"&\n\x11LessonByIdRequest\x12\x11\n\tlesson_id\x18\x01 \x01(\x03"b\n\x15LessonsByGroupRequest\x12\x10\n\x08group_id\x18\x01 \x01(\x03\x12\x13\n\x0bsemester_id\x18\x02 \x01(\x03\x12\x11\n\tdate_from\x18\x03 \x01(\t\x12\x0f\n\x07\x64\x61te_to\x18\x04 \x01(\t"\xf1\x01\n\x0eLessonResponse\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x18\n\x10schedule_item_id\x18\x02 \x01(\x03\x12\x10\n\x08group_id\x18\x03 \x01(\x03\x12\x12\n\nsubject_id\x18\x04 \x01(\x03\x12\x12\n\nteacher_id\x18\x05 \x01(\x03\x12\x0c\n\x04\x64\x61te\x18\x06 \x01(\t\x12\x15\n\rlesson_number\x18\x07 \x01(\x05\x12\x12\n\nstart_time\x18\x08 \x01(\t\x12\x10\n\x08\x65nd_time\x18\t \x01(\t\x12\x0e\n\x06status\x18\n \x01(\t\x12\x16\n\x0eis_geo_blocked\x18\x0b \x01(\x08\x12\x0c\n\x04room\x18\x0c \x01(\t"K\n\x0fLessonsResponse\x12\x38\n\x07lessons\x18\x01 \x03(\x0b\x32\'.rutcampustrack.schedule.LessonResponse2\xd4\x02\n\x13ScheduleGrpcService\x12h\n\x0fGetActiveLesson\x12,.rutcampustrack.schedule.ActiveLessonRequest\x1a\'.rutcampustrack.schedule.LessonResponse\x12\x64\n\rGetLessonById\x12*.rutcampustrack.schedule.LessonByIdRequest\x1a\'.rutcampustrack.schedule.LessonResponse\x12m\n\x11GetLessonsByGroup\x12..rutcampustrack.schedule.LessonsByGroupRequest\x1a(.rutcampustrack.schedule.LessonsResponseB#\n\x1fru.rutcampustrack.schedule.grpcP\x01\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "schedule_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals["DESCRIPTOR"]._loaded_options = None
    _globals["DESCRIPTOR"]._serialized_options = b"\n\037ru.rutcampustrack.schedule.grpcP\001"
    _globals["_ACTIVELESSONREQUEST"]._serialized_start = 43
    _globals["_ACTIVELESSONREQUEST"]._serialized_end = 101
    _globals["_LESSONBYIDREQUEST"]._serialized_start = 103
    _globals["_LESSONBYIDREQUEST"]._serialized_end = 141
    _globals["_LESSONSBYGROUPREQUEST"]._serialized_start = 143
    _globals["_LESSONSBYGROUPREQUEST"]._serialized_end = 241
    _globals["_LESSONRESPONSE"]._serialized_start = 244
    _globals["_LESSONRESPONSE"]._serialized_end = 485
    _globals["_LESSONSRESPONSE"]._serialized_start = 487
    _globals["_LESSONSRESPONSE"]._serialized_end = 562
    _globals["_SCHEDULEGRPCSERVICE"]._serialized_start = 565
    _globals["_SCHEDULEGRPCSERVICE"]._serialized_end = 905
# @@protoc_insertion_point(module_scope)
