# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client stubs for proto/attendance.proto."""

import grpc

from bot.grpc_client import attendance_pb2 as attendance__pb2


class AttendanceRequestBotGrpcServiceStub:
    """Generated asynchronous client for the bot attachment service."""

    def __init__(self, channel):
        self.FetchExcuseAttachment = channel.unary_unary(
            "/rutcampustrack.attendance.AttendanceRequestBotGrpcService/FetchExcuseAttachment",
            request_serializer=attendance__pb2.FetchExcuseAttachmentRequest.SerializeToString,
            response_deserializer=attendance__pb2.FetchExcuseAttachmentResponse.FromString,
        )


class AttendanceRequestBotGrpcServiceServicer:
    def FetchExcuseAttachment(self, request, context):
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_AttendanceRequestBotGrpcServiceServicer_to_server(servicer, server):
    handlers = {
        "FetchExcuseAttachment": grpc.unary_unary_rpc_method_handler(
            servicer.FetchExcuseAttachment,
            request_deserializer=attendance__pb2.FetchExcuseAttachmentRequest.FromString,
            response_serializer=attendance__pb2.FetchExcuseAttachmentResponse.SerializeToString,
        ),
    }
    server.add_generic_rpc_handlers((grpc.method_handlers_generic_handler(
        "rutcampustrack.attendance.AttendanceRequestBotGrpcService", handlers
    ),))
