-- B0 campus map foundation. The catalog is server-owned and deliberately has
-- no seed inventory, provider, HTTP or configuration wiring in this migration.
-- Flyway owns the transaction.

CREATE EXTENSION IF NOT EXISTS pgcrypto WITH SCHEMA public;

CREATE TABLE campus_map_catalog_revision
(
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    revision                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    schema_version            INTEGER NOT NULL DEFAULT 1,
    validation_policy_version INTEGER NOT NULL DEFAULT 1,
    is_current                BOOLEAN NOT NULL DEFAULT FALSE,
    created_at                TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT campus_map_catalog_revision_id_positive_chk CHECK (id > 0),
    CONSTRAINT campus_map_catalog_revision_positive_chk CHECK (revision > 0),
    CONSTRAINT campus_map_catalog_revision_schema_positive_chk CHECK (schema_version > 0),
    CONSTRAINT campus_map_catalog_revision_policy_positive_chk
        CHECK (validation_policy_version > 0),
    CONSTRAINT campus_map_catalog_revision_revision_uq UNIQUE (revision)
);

CREATE UNIQUE INDEX uq_campus_map_catalog_current
    ON campus_map_catalog_revision (is_current)
    WHERE is_current;

CREATE TABLE campus_map_building
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code           VARCHAR(64) NOT NULL,
    label          VARCHAR(255) NOT NULL,
    display_order  INTEGER NOT NULL CHECK (display_order >= 0),
    is_active      BOOLEAN NOT NULL DEFAULT TRUE,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT campus_map_building_id_positive_chk CHECK (id > 0),
    CONSTRAINT campus_map_building_code_uq UNIQUE (code)
);

CREATE TABLE campus_map_floor
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    building_id        BIGINT NOT NULL,
    code               VARCHAR(64) NOT NULL,
    label              VARCHAR(255) NOT NULL,
    display_order      INTEGER NOT NULL CHECK (display_order >= 0),
    current_version_id BIGINT,
    is_active           BOOLEAN NOT NULL DEFAULT TRUE,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT campus_map_floor_building_fk
        FOREIGN KEY (building_id) REFERENCES campus_map_building (id) ON DELETE RESTRICT,
    CONSTRAINT campus_map_floor_id_positive_chk CHECK (id > 0),
    CONSTRAINT campus_map_floor_building_code_uq UNIQUE (building_id, code),
    CONSTRAINT campus_map_floor_id_building_uq UNIQUE (id, building_id)
);

CREATE TABLE campus_map_plan_version
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    floor_id            BIGINT NOT NULL,
    version             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    catalog_revision_id BIGINT,
    label               VARCHAR(255) NOT NULL,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    published_at        TIMESTAMPTZ,

    CONSTRAINT campus_map_plan_version_id_positive_chk CHECK (id > 0),
    CONSTRAINT campus_map_plan_version_positive_chk CHECK (version > 0),
    CONSTRAINT campus_map_plan_version_floor_fk
        FOREIGN KEY (floor_id) REFERENCES campus_map_floor (id) ON DELETE RESTRICT,
    CONSTRAINT campus_map_plan_version_catalog_fk
        FOREIGN KEY (catalog_revision_id)
        REFERENCES campus_map_catalog_revision (id) ON DELETE RESTRICT,
    CONSTRAINT campus_map_plan_version_floor_version_uq UNIQUE (floor_id, version),
    CONSTRAINT campus_map_plan_version_id_floor_uq UNIQUE (id, floor_id)
);

CREATE OR REPLACE FUNCTION protect_campus_map_plan_version()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    -- A publication update and a draft graph edit both serialize on this row.
    PERFORM 1
    FROM campus_map_plan_version
    WHERE id = OLD.id
    FOR UPDATE;

    IF TG_OP = 'DELETE' THEN
        IF OLD.published_at IS NOT NULL THEN
            RAISE EXCEPTION 'published campus map plan version is immutable';
        END IF;
        RETURN OLD;
    END IF;

    IF NEW.id IS DISTINCT FROM OLD.id
       OR NEW.floor_id IS DISTINCT FROM OLD.floor_id
       OR NEW.version IS DISTINCT FROM OLD.version
       OR NEW.catalog_revision_id IS DISTINCT FROM OLD.catalog_revision_id THEN
        RAISE EXCEPTION 'campus map plan version identity is immutable';
    END IF;

    IF OLD.published_at IS NOT NULL THEN
        IF NEW.published_at IS DISTINCT FROM OLD.published_at
           OR NEW.label IS DISTINCT FROM OLD.label
           OR NEW.created_at IS DISTINCT FROM OLD.created_at THEN
            RAISE EXCEPTION 'published campus map plan version is immutable';
        END IF;
    END IF;

    RETURN NEW;
END
$$;

CREATE TRIGGER campus_map_plan_version_identity_guard_trg
    BEFORE UPDATE OR DELETE ON campus_map_plan_version
    FOR EACH ROW
    EXECUTE FUNCTION protect_campus_map_plan_version();

ALTER TABLE campus_map_floor
    ADD CONSTRAINT campus_map_floor_current_version_fk
        FOREIGN KEY (current_version_id, id)
        REFERENCES campus_map_plan_version (id, floor_id)
        ON DELETE RESTRICT
        DEFERRABLE INITIALLY DEFERRED;

CREATE TABLE campus_map_asset
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_version_id BIGINT NOT NULL,
    format          VARCHAR(8) NOT NULL,
    content_type    VARCHAR(64) NOT NULL,
    content         BYTEA NOT NULL,
    bytes           BIGINT NOT NULL,
    sha256          BYTEA NOT NULL,
    width           INTEGER,
    height          INTEGER,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT campus_map_asset_id_positive_chk CHECK (id > 0),
    CONSTRAINT campus_map_asset_version_fk
        FOREIGN KEY (plan_version_id) REFERENCES campus_map_plan_version (id) ON DELETE RESTRICT,
    CONSTRAINT campus_map_asset_format_chk CHECK (format IN ('PNG', 'SVG')),
    CONSTRAINT campus_map_asset_content_type_chk
        CHECK ((format = 'PNG' AND content_type = 'image/png')
            OR (format = 'SVG' AND content_type = 'image/svg+xml')),
    CONSTRAINT campus_map_asset_bytes_chk
        CHECK (bytes > 0 AND bytes <= 10485760 AND octet_length(content) = bytes),
    CONSTRAINT campus_map_asset_sha256_chk
        CHECK (octet_length(sha256) = 32 AND sha256 = public.digest(content, 'sha256')),
    CONSTRAINT campus_map_asset_dimensions_chk
        CHECK ((width IS NULL OR width > 0) AND (height IS NULL OR height > 0)),
    CONSTRAINT campus_map_asset_identity_uq UNIQUE (id, plan_version_id, format)
);

CREATE TABLE campus_map_plan_format
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_version_id BIGINT NOT NULL,
    format          VARCHAR(8) NOT NULL,
    state           VARCHAR(16) NOT NULL,
    content_type    VARCHAR(64) NOT NULL,
    asset_id        BIGINT,
    bytes           BIGINT NOT NULL DEFAULT 0,
    sha256          BYTEA,
    width           INTEGER,
    height          INTEGER,
    view_box        DOUBLE PRECISION[],
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT campus_map_plan_format_id_positive_chk CHECK (id > 0),
    CONSTRAINT campus_map_plan_format_version_fk
        FOREIGN KEY (plan_version_id) REFERENCES campus_map_plan_version (id) ON DELETE RESTRICT,
    CONSTRAINT campus_map_plan_format_format_chk CHECK (format IN ('PNG', 'SVG')),
    CONSTRAINT campus_map_plan_format_state_chk
        CHECK (state IN ('ABSENT', 'PROCESSING', 'READY', 'FAILED')),
    CONSTRAINT campus_map_plan_format_content_type_chk
        CHECK ((format = 'PNG' AND content_type = 'image/png')
            OR (format = 'SVG' AND content_type = 'image/svg+xml')),
    CONSTRAINT campus_map_plan_format_bytes_chk
        CHECK (bytes >= 0 AND bytes <= 10485760),
    CONSTRAINT campus_map_plan_format_sha256_chk
        CHECK (sha256 IS NULL OR octet_length(sha256) = 32),
    CONSTRAINT campus_map_plan_format_dimensions_chk
        CHECK ((width IS NULL OR width > 0) AND (height IS NULL OR height > 0)),
    CONSTRAINT campus_map_plan_format_view_box_chk
        CHECK (view_box IS NULL OR cardinality(view_box) = 4),
    CONSTRAINT campus_map_plan_format_ready_state_chk
        CHECK (
            (state = 'READY'
             AND asset_id IS NOT NULL
             AND bytes > 0
             AND sha256 IS NOT NULL)
            OR
            (state <> 'READY'
             AND asset_id IS NULL
             AND bytes = 0
             AND sha256 IS NULL)
        ),
    CONSTRAINT campus_map_plan_format_version_format_uq UNIQUE (plan_version_id, format)
);

ALTER TABLE campus_map_plan_format
    ADD CONSTRAINT campus_map_plan_format_asset_fk
        FOREIGN KEY (asset_id, plan_version_id, format)
        REFERENCES campus_map_asset (id, plan_version_id, format)
        ON DELETE RESTRICT;

CREATE OR REPLACE FUNCTION validate_campus_map_ready_asset()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    asset_record       campus_map_asset%ROWTYPE;
    plan_version_id    BIGINT;
    plan_published_at  TIMESTAMPTZ;
BEGIN
    plan_version_id := CASE WHEN TG_OP = 'DELETE' THEN OLD.plan_version_id ELSE NEW.plan_version_id END;

    SELECT published_at INTO plan_published_at
    FROM campus_map_plan_version
    WHERE id = plan_version_id
    FOR UPDATE;
    IF NOT FOUND THEN
        RAISE EXCEPTION 'campus map plan version % does not exist', plan_version_id;
    END IF;

    IF TG_OP = 'UPDATE'
       AND (NEW.plan_version_id IS DISTINCT FROM OLD.plan_version_id
            OR NEW.format IS DISTINCT FROM OLD.format) THEN
        RAISE EXCEPTION 'campus map plan format identity is immutable';
    END IF;
    IF plan_published_at IS NOT NULL THEN
        RAISE EXCEPTION 'published campus map plan format is immutable';
    END IF;
    IF TG_OP = 'DELETE' THEN
        RETURN OLD;
    END IF;

    IF NEW.state = 'READY' THEN
        SELECT asset.* INTO asset_record
        FROM campus_map_asset AS asset
        WHERE asset.id = NEW.asset_id
          AND asset.plan_version_id = NEW.plan_version_id
          AND asset.format = NEW.format;

        IF NOT FOUND THEN
            RAISE EXCEPTION 'ready campus map format requires a matching immutable asset';
        END IF;
        IF asset_record.bytes <> NEW.bytes
           OR asset_record.sha256 IS DISTINCT FROM NEW.sha256
           OR asset_record.content_type <> NEW.content_type
           OR asset_record.width IS DISTINCT FROM NEW.width
           OR asset_record.height IS DISTINCT FROM NEW.height THEN
            RAISE EXCEPTION 'ready campus map format metadata does not match its asset';
        END IF;
    END IF;
    RETURN NEW;
END
$$;

CREATE TRIGGER campus_map_plan_format_asset_guard_trg
    BEFORE INSERT OR UPDATE OR DELETE ON campus_map_plan_format
    FOR EACH ROW
    EXECUTE FUNCTION validate_campus_map_ready_asset();

CREATE OR REPLACE FUNCTION protect_campus_map_asset()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    RAISE EXCEPTION 'campus map assets are immutable and retained';
END
$$;

CREATE TRIGGER campus_map_asset_immutable_trg
    BEFORE UPDATE OR DELETE ON campus_map_asset
    FOR EACH ROW
    EXECUTE FUNCTION protect_campus_map_asset();

CREATE INDEX idx_campus_map_floor_order
    ON campus_map_floor (building_id, display_order, id);

CREATE INDEX idx_campus_map_building_order
    ON campus_map_building (display_order, id);

CREATE TABLE campus_map_floor_daily_demand
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    floor_id    BIGINT NOT NULL,
    utc_day     DATE NOT NULL,
    open_count  BIGINT NOT NULL DEFAULT 0,
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT campus_map_floor_daily_demand_id_positive_chk CHECK (id > 0),
    CONSTRAINT campus_map_floor_daily_demand_count_chk CHECK (open_count >= 0),
    CONSTRAINT campus_map_floor_daily_demand_floor_fk
        FOREIGN KEY (floor_id) REFERENCES campus_map_floor (id) ON DELETE RESTRICT,
    CONSTRAINT campus_map_floor_daily_demand_floor_day_uq UNIQUE (floor_id, utc_day)
);

CREATE TABLE campus_map_open_intent
(
    owner_hmac       BYTEA NOT NULL,
    intent_id        UUID NOT NULL,
    building_id      BIGINT NOT NULL,
    floor_id         BIGINT NOT NULL,
    payload_hash     BYTEA NOT NULL,
    accepted_utc_day DATE NOT NULL,
    accepted_at      TIMESTAMPTZ NOT NULL,
    expires_at       TIMESTAMPTZ NOT NULL,

    CONSTRAINT campus_map_open_intent_pk PRIMARY KEY (owner_hmac, intent_id),
    CONSTRAINT campus_map_open_intent_owner_hmac_chk CHECK (octet_length(owner_hmac) = 32),
    CONSTRAINT campus_map_open_intent_payload_hash_chk CHECK (octet_length(payload_hash) = 32),
    CONSTRAINT campus_map_open_intent_expiry_chk
        CHECK (expires_at = accepted_at + INTERVAL '48 hours'),
    CONSTRAINT campus_map_open_intent_floor_building_fk
        FOREIGN KEY (floor_id, building_id)
        REFERENCES campus_map_floor (id, building_id) ON DELETE RESTRICT,
    CONSTRAINT campus_map_open_intent_utc_day_chk
        CHECK (accepted_utc_day = (accepted_at AT TIME ZONE 'UTC')::date),
    CONSTRAINT campus_map_open_intent_dedupe_identity_uq
        UNIQUE (owner_hmac, intent_id, floor_id, accepted_utc_day)
);

CREATE OR REPLACE FUNCTION protect_campus_map_open_intent()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    IF TG_OP = 'UPDATE' THEN
        IF NEW.owner_hmac IS DISTINCT FROM OLD.owner_hmac
           OR NEW.intent_id IS DISTINCT FROM OLD.intent_id
           OR NEW.building_id IS DISTINCT FROM OLD.building_id
           OR NEW.floor_id IS DISTINCT FROM OLD.floor_id
           OR NEW.payload_hash IS DISTINCT FROM OLD.payload_hash
           OR NEW.accepted_utc_day IS DISTINCT FROM OLD.accepted_utc_day
           OR NEW.accepted_at IS DISTINCT FROM OLD.accepted_at
           OR NEW.expires_at IS DISTINCT FROM OLD.expires_at THEN
            RAISE EXCEPTION 'campus map open intent identity is immutable';
        END IF;
        RETURN NEW;
    END IF;

    IF OLD.expires_at > CURRENT_TIMESTAMP THEN
        RAISE EXCEPTION 'campus map open intent cannot be removed before expiry';
    END IF;
    RETURN OLD;
END
$$;

CREATE TRIGGER campus_map_open_intent_guard_trg
    BEFORE UPDATE OR DELETE ON campus_map_open_intent
    FOR EACH ROW
    EXECUTE FUNCTION protect_campus_map_open_intent();

CREATE TABLE campus_map_floor_demand_dedupe
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_hmac     BYTEA NOT NULL,
    floor_id       BIGINT NOT NULL,
    utc_day        DATE NOT NULL,
    intent_id      UUID NOT NULL,
    accepted_at    TIMESTAMPTZ NOT NULL,

    CONSTRAINT campus_map_floor_demand_dedupe_id_positive_chk CHECK (id > 0),
    CONSTRAINT campus_map_floor_demand_dedupe_owner_hmac_chk
        CHECK (octet_length(owner_hmac) = 32),
    CONSTRAINT campus_map_floor_demand_dedupe_floor_fk
        FOREIGN KEY (floor_id) REFERENCES campus_map_floor (id) ON DELETE RESTRICT,
    CONSTRAINT campus_map_floor_demand_dedupe_owner_floor_day_uq
        UNIQUE (owner_hmac, floor_id, utc_day),
    CONSTRAINT campus_map_floor_demand_dedupe_owner_intent_uq
        UNIQUE (owner_hmac, intent_id)
);

CREATE OR REPLACE FUNCTION increment_campus_map_floor_demand()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    intent_record campus_map_open_intent%ROWTYPE;
BEGIN
    SELECT * INTO intent_record
    FROM campus_map_open_intent
    WHERE owner_hmac = NEW.owner_hmac
      AND intent_id = NEW.intent_id
    FOR UPDATE;

    IF NOT FOUND
       OR intent_record.floor_id <> NEW.floor_id
       OR intent_record.accepted_utc_day <> NEW.utc_day
       OR intent_record.accepted_at IS DISTINCT FROM NEW.accepted_at THEN
        RAISE EXCEPTION 'campus map demand dedupe does not match its open intent';
    END IF;

    -- This trigger runs only for an actual INSERT. A conflicting retry does
    -- not create a dedupe row and therefore cannot inflate the aggregate.
    INSERT INTO campus_map_floor_daily_demand (floor_id, utc_day, open_count)
    VALUES (NEW.floor_id, NEW.utc_day, 1)
    ON CONFLICT (floor_id, utc_day)
    DO UPDATE SET open_count = campus_map_floor_daily_demand.open_count + 1,
                  updated_at = NOW();
    RETURN NEW;
END
$$;

CREATE TRIGGER campus_map_floor_demand_dedupe_count_trg
    AFTER INSERT ON campus_map_floor_demand_dedupe
    FOR EACH ROW
    EXECUTE FUNCTION increment_campus_map_floor_demand();

CREATE OR REPLACE FUNCTION protect_campus_map_demand_dedupe()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    IF TG_OP = 'UPDATE' THEN
        RAISE EXCEPTION 'campus map demand dedupe is immutable';
    END IF;

    -- Retain the daily key through the end of its UTC day plus 48 hours,
    -- independent of the particular intent acceptance time.
    IF (OLD.utc_day::timestamp + INTERVAL '3 days')
       > (CURRENT_TIMESTAMP AT TIME ZONE 'UTC') THEN
        RAISE EXCEPTION 'campus map demand dedupe cannot be removed before UTC retention';
    END IF;
    RETURN OLD;
END
$$;

CREATE TRIGGER campus_map_floor_demand_dedupe_immutable_trg
    BEFORE UPDATE OR DELETE ON campus_map_floor_demand_dedupe
    FOR EACH ROW
    EXECUTE FUNCTION protect_campus_map_demand_dedupe();
