import type {} from './vue-runtime-dom.d.ts'
import type { components, operations, paths } from './api/generated/mobile-bff'
export type { components as authComponents, operations as authOperations, paths as authPaths } from './api/generated/auth'

export type { components, operations, paths }

export type StudentSession = components['schemas']['StudentSession']
export type StudentToday = components['schemas']['StudentToday']
export type StudentSemesterSchedule =
  components['schemas']['StudentSemesterSchedule']
export type StudentCheckinCommand =
  components['schemas']['StudentCheckinCommand']
export type StudentCheckinAck = components['schemas']['StudentCheckinAck']
export type MobileProblemDetails =
  components['schemas']['MobileProblemDetails']
export * from './api/student-client'
export * from './api/map-client'
export * from './features/admin-semester/admin-semester-client'
export * from './features/admin-dashboard/admin-dashboard-client'
export * from './features/admin-users/admin-users-client'
export * from './features/admin-groups/admin-groups-client'
export * from './api/types'
export * from './domain/checkin'
export * from './domain/offline-today'
export * from './domain/homework'
export * from './domain/recoverable-read'
export * from './offline/semester-snapshot'
export * from './test-adapter/fixture-transport'
export * from './features/today/use-today'
export * from './features/homework/use-homework'
export * from './features/homework/headman-homework-client'
export * from './features/attendance/use-attendance'
export { default as AttendanceScreen } from './features/attendance/AttendanceScreen.vue'
export * from './features/statistics/use-statistics'
export { default as StatisticsScreen } from './features/statistics/StatisticsScreen.vue'
export { default as TodayScreen } from './features/today/TodayScreen.vue'
export { default as HomeworkScreen } from './features/homework/HomeworkScreen.vue'
export { default as AssistantHomeworkScreen } from './features/homework/AssistantHomeworkScreen.vue'
export type * from './features/profile/profile-types'
export * from './features/schedule/headman-schedule-client'
export { default as HeadmanScheduleScreen } from './features/schedule/HeadmanScheduleScreen.vue'
export { default as MapScreen } from './features/map/MapScreen.vue'
export { default as AdminMapScreen } from './features/admin-map/AdminMapScreen.vue'
export { default as AdminSemesterScreen } from './features/admin-semester/AdminSemesterScreen.vue'
export { default as AdminDashboardScreen } from './features/admin-dashboard/AdminDashboardScreen.vue'
export { default as AdminRoleNavigation } from './features/admin-semester/AdminRoleNavigation.vue'
export { default as AdminUsersScreen } from './features/admin-users/AdminUsersScreen.vue'
export { default as AdminGroupsScreen } from './features/admin-groups/AdminGroupsScreen.vue'
export * from './features/headman-journal/headman-journal-client'
export { default as HeadmanJournalScreen } from './features/headman-journal/HeadmanJournalScreen.vue'
export * from './features/headman-requests/headman-requests-client'
export { default as HeadmanRequestsScreen } from './features/headman-requests/HeadmanRequestsScreen.vue'
export * from './features/headman-group/headman-group-client'
export { default as AssistantActionsScreen } from './features/headman-group/AssistantActionsScreen.vue'
export { default as HeadmanGroupScreen } from './features/headman-group/HeadmanGroupScreen.vue'
export * from './features/headman-subjects/headman-subjects-client'
export { default as HeadmanSubjectsScreen } from './features/headman-subjects/HeadmanSubjectsScreen.vue'
export * from './features/headman-stats/headman-stats-client'
export { default as HeadmanStatsScreen } from './features/headman-stats/HeadmanStatsScreen.vue'
export * from './features/notifications/notifications-client'
export { default as NotificationsEntryButton } from './features/notifications/NotificationsEntryButton.vue'
export { default as NotificationsScreen } from './features/notifications/NotificationsScreen.vue'
export { ProfileRequestError } from './features/profile/profile-types'
export { ProfileState } from './features/profile/profile-state'
export type { ProfileStateView, ProfileResourceStatus } from './features/profile/profile-state'
export { default as ProfileScreen } from './features/profile/ProfileScreen.vue'
export { default as RoleSwitchScreen } from './features/profile/RoleSwitchScreen.vue'
export { default as AppearanceScreen } from './features/profile/AppearanceScreen.vue'
export { default as SecurityScreen } from './features/profile/SecurityScreen.vue'
export { default as SessionsScreen } from './features/profile/SessionsScreen.vue'
export { default as AccountHistoryScreen } from './features/profile/AccountHistoryScreen.vue'
export * from './features/teacher/teacher-client'
export { default as TeacherFeatureOwner } from './shared/components/TeacherFeatureOwner.vue'
export { default as TeacherHomeScreen } from './features/teacher/TeacherHomeScreen.vue'
export { default as TeacherLessonScreen } from './features/teacher/TeacherLessonScreen.vue'
export { default as TeacherJournalScreen } from './features/teacher/TeacherJournalScreen.vue'
export { default as TeacherExcuseScreen } from './features/teacher/TeacherExcuseScreen.vue'
export { default as TeacherStatsScreen } from './features/teacher/TeacherStatsScreen.vue'
export type * from './features/requests/types'
export * from './features/requests/state'
export * from './features/requests/requests-port'
export * from './features/requests/requests-controller'
export * from './features/requests/use-requests'
export { default as RequestsScreen } from './features/requests/RequestsScreen.vue'
export { default as RequestCard } from './features/requests/RequestCard.vue'
export { default as RequestTypeScreen } from './features/requests/RequestTypeScreen.vue'
export { default as ExcuseRequestScreen } from './features/requests/ExcuseRequestScreen.vue'
export { default as LateCheckinRequestScreen } from './features/requests/LateCheckinRequestScreen.vue'
export { default as RequestLessonSelector } from './features/requests/RequestLessonSelector.vue'
export { default as RequestAttachmentField } from './features/requests/RequestAttachmentField.vue'
export { default as MobileBottomNav } from './shared/components/MobileBottomNav.vue'
export { default as MobileShell } from './shared/components/MobileShell.vue'
export { default as StudentFeatureOwner } from './shared/components/StudentFeatureOwner.vue'
export * from './shared/navigation'
export * from './shared/mobile-navigation-items'
export * from './shared/profile-owner-status'
export * from './shared/theme'
export * from './shared/shell-contract'
export * from './shared/session-owner'
export * from './shared/report-download-client'
export type * from './shared/host'
