server:
  port: 9094

spring:
  application:
    name: notification-web

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: ${RABBITMQ_USER:rct_user}
    password: ${RABBITMQ_PASSWORD:rct_dev_pass}

notification:
  jwt:
    public-key-path: ${JWT_PUBLIC_KEY_PATH:/keys/public.key}

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never

logging:
  level:
    ru.rutcampustrack: DEBUG
