-- Canonical recurring CREATE dependency for V17.
-- The fence is the local serialization authority for every physical row.

CREATE TABLE schedule_assignment_fences
(
    assignment_id          BIGINT PRIMARY KEY,
    group_id               BIGINT       NOT NULL,
    subject_id             BIGINT       NOT NULL,
    semester_id            BIGINT       NOT NULL,
    assigned_teacher_id   BIGINT       NOT NULL,
    lesson_type            VARCHAR(16)  NOT NULL,
    valid_from             DATE         NOT NULL,
    cap_until_exclusive    DATE         NOT NULL,
    revision                BIGINT       NOT NULL DEFAULT 1,
    created_at              TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT schedule_assignment_fences_assignment_chk CHECK (assignment_id > 0),
    CONSTRAINT schedule_assignment_fences_group_chk CHECK (group_id > 0),
    CONSTRAINT schedule_assignment_fences_subject_chk CHECK (subject_id > 0),
    CONSTRAINT schedule_assignment_fences_semester_chk CHECK (semester_id > 0),
    CONSTRAINT schedule_assignment_fences_teacher_chk CHECK (assigned_teacher_id > 0),
    CONSTRAINT schedule_assignment_fences_type_chk
        CHECK (lesson_type IN ('lecture', 'practice', 'lab')),
    CONSTRAINT schedule_assignment_fences_interval_chk
        CHECK (cap_until_exclusive > valid_from),
    CONSTRAINT schedule_assignment_fences_revision_chk CHECK (revision > 0)
);

CREATE TABLE schedule_recurring_create_replay
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_id              BIGINT       NOT NULL,
    request_key           UUID         NOT NULL,
    payload_hash          BYTEA        NOT NULL,
    schedule_item_id      BIGINT       NOT NULL,
    assignment_id         BIGINT       NOT NULL,
    generated_count       BIGINT       NOT NULL,
    generated_from        DATE,
    generated_until       DATE,
    created_at            TIMESTAMPTZ  NOT NULL DEFAULT NOW(),

    CONSTRAINT schedule_recurring_replay_id_chk CHECK (id > 0),
    CONSTRAINT schedule_recurring_replay_actor_chk CHECK (actor_id > 0),
    CONSTRAINT schedule_recurring_replay_hash_chk CHECK (octet_length(payload_hash) = 32),
    CONSTRAINT schedule_recurring_replay_item_fk
        FOREIGN KEY (schedule_item_id) REFERENCES schedule_items (id) ON DELETE RESTRICT,
    CONSTRAINT schedule_recurring_replay_assignment_chk CHECK (assignment_id > 0),
    CONSTRAINT schedule_recurring_replay_count_chk CHECK (generated_count >= 0),
    CONSTRAINT schedule_recurring_replay_range_chk
        CHECK (generated_count = 0 OR (generated_from IS NOT NULL AND generated_until IS NOT NULL)),
    CONSTRAINT schedule_recurring_replay_actor_key_uq UNIQUE (actor_id, request_key)
);

ALTER TABLE schedule_items
    ADD COLUMN generated_count BIGINT,
    ADD COLUMN generated_from DATE,
    ADD COLUMN generated_until DATE;

ALTER TABLE lessons
    -- V17 rows may already be retained. Do not invent historical snapshot
    -- values; new canonical inserts are required to provide both fields by
    -- the INSERT guard below.
    ADD COLUMN day_of_week SMALLINT,
    ADD COLUMN week_type_snapshot VARCHAR(8),
    ADD CONSTRAINT lessons_day_of_week_chk CHECK (day_of_week BETWEEN 1 AND 7),
    ADD CONSTRAINT lessons_week_type_snapshot_chk
        CHECK (week_type_snapshot IN ('all', 'odd', 'even'));

CREATE INDEX idx_schedule_assignment_fences_interval
    ON schedule_assignment_fences (group_id, semester_id, cap_until_exclusive);

CREATE OR REPLACE FUNCTION protect_schedule_item_assignment_provenance()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    IF TG_OP = 'UPDATE'
       AND (NEW.assignment_id IS DISTINCT FROM OLD.assignment_id
            OR NEW.group_id IS DISTINCT FROM OLD.group_id
            OR NEW.subject_id IS DISTINCT FROM OLD.subject_id
            OR NEW.semester_id IS DISTINCT FROM OLD.semester_id) THEN
        RAISE EXCEPTION 'schedule item assignment provenance is immutable';
    END IF;
    RETURN NEW;
END
$$;

CREATE TRIGGER schedule_items_assignment_provenance_guard_trg
    BEFORE UPDATE ON schedule_items
    FOR EACH ROW
    EXECUTE FUNCTION protect_schedule_item_assignment_provenance();

CREATE OR REPLACE FUNCTION protect_schedule_assignment_fence()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'assignment fences are retained';
    END IF;

    IF NEW.assignment_id IS DISTINCT FROM OLD.assignment_id
       OR NEW.group_id IS DISTINCT FROM OLD.group_id
       OR NEW.subject_id IS DISTINCT FROM OLD.subject_id
       OR NEW.semester_id IS DISTINCT FROM OLD.semester_id
       OR NEW.assigned_teacher_id IS DISTINCT FROM OLD.assigned_teacher_id
       OR NEW.lesson_type IS DISTINCT FROM OLD.lesson_type
       OR NEW.valid_from IS DISTINCT FROM OLD.valid_from THEN
        RAISE EXCEPTION 'assignment fence provenance is immutable';
    END IF;
    IF NEW.revision < OLD.revision THEN
        RAISE EXCEPTION 'assignment fence revision cannot move backwards';
    END IF;
    IF NEW.cap_until_exclusive > OLD.cap_until_exclusive THEN
        RAISE EXCEPTION 'assignment fence cap cannot widen';
    END IF;
    IF NEW.cap_until_exclusive < OLD.cap_until_exclusive THEN
        IF EXISTS (
            SELECT 1
              FROM lessons
             WHERE assignment_id = OLD.assignment_id
               AND date >= NEW.cap_until_exclusive
             LIMIT 1
        ) THEN
            RAISE EXCEPTION 'assignment fence cap cannot exclude retained lessons';
        END IF;
        IF EXISTS (
            SELECT 1
              FROM lesson_occurrences
             WHERE assignment_id = OLD.assignment_id
               AND occurrence_date >= NEW.cap_until_exclusive
             LIMIT 1
        ) THEN
            RAISE EXCEPTION 'assignment fence cap cannot exclude retained occurrences';
        END IF;
    END IF;
    RETURN NEW;
END
$$;

CREATE TRIGGER schedule_assignment_fences_guard_trg
    BEFORE UPDATE OR DELETE ON schedule_assignment_fences
    FOR EACH ROW
    EXECUTE FUNCTION protect_schedule_assignment_fence();

CREATE OR REPLACE FUNCTION validate_recurring_occurrence_fence()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    fence_record schedule_assignment_fences%ROWTYPE;
BEGIN
    SELECT * INTO fence_record
      FROM schedule_assignment_fences
     WHERE assignment_id = NEW.assignment_id
     FOR UPDATE;
    IF NOT FOUND THEN
        RAISE EXCEPTION 'assignment fence % does not exist', NEW.assignment_id;
    END IF;
    IF NEW.schedule_item_id IS NULL
       OR NEW.assignment_id IS DISTINCT FROM fence_record.assignment_id
       OR NEW.group_id IS DISTINCT FROM fence_record.group_id
       OR NEW.subject_id IS DISTINCT FROM fence_record.subject_id
       OR NEW.semester_id IS DISTINCT FROM fence_record.semester_id
       OR NEW.assigned_teacher_id IS DISTINCT FROM fence_record.assigned_teacher_id
       OR NEW.lesson_type IS DISTINCT FROM fence_record.lesson_type
       OR NEW.occurrence_date < fence_record.valid_from
       OR NEW.occurrence_date >= fence_record.cap_until_exclusive THEN
        RAISE EXCEPTION 'recurring occurrence violates assignment fence %', NEW.assignment_id;
    END IF;
    RETURN NEW;
END
$$;

CREATE TRIGGER lesson_occurrences_fence_guard_trg
    BEFORE INSERT ON lesson_occurrences
    FOR EACH ROW
    EXECUTE FUNCTION validate_recurring_occurrence_fence();

CREATE OR REPLACE FUNCTION validate_lesson_insert_fence()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    fence_record schedule_assignment_fences%ROWTYPE;
BEGIN
    IF NEW.day_of_week IS NULL OR NEW.week_type_snapshot IS NULL THEN
        RAISE EXCEPTION 'new physical lessons require immutable schedule snapshots';
    END IF;
    SELECT * INTO fence_record
      FROM schedule_assignment_fences
     WHERE assignment_id = NEW.assignment_id
     FOR UPDATE;
    IF NOT FOUND THEN
        RAISE EXCEPTION 'assignment fence % does not exist', NEW.assignment_id;
    END IF;
    IF NEW.assignment_id IS DISTINCT FROM fence_record.assignment_id
       OR NEW.group_id IS DISTINCT FROM fence_record.group_id
       OR NEW.subject_id IS DISTINCT FROM fence_record.subject_id
       OR NEW.semester_id IS DISTINCT FROM fence_record.semester_id
       OR NEW.assigned_teacher_id IS DISTINCT FROM fence_record.assigned_teacher_id
       OR NEW.lesson_type IS DISTINCT FROM fence_record.lesson_type
       OR NEW.date < fence_record.valid_from
       OR NEW.date >= fence_record.cap_until_exclusive THEN
        RAISE EXCEPTION 'physical lesson identity snapshot violates its occurrence/fence';
    END IF;
    RETURN NEW;
END
$$;

CREATE OR REPLACE FUNCTION validate_lesson_physical_snapshot()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    occurrence_record lesson_occurrences%ROWTYPE;
BEGIN
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'physical lessons are retained; use a lifecycle state';
    END IF;

    SELECT * INTO occurrence_record
      FROM lesson_occurrences
     WHERE id = NEW.occurrence_id;
    IF NOT FOUND THEN
        RAISE EXCEPTION 'lesson occurrence % does not exist', NEW.occurrence_id;
    END IF;

    IF NEW.occurrence_id IS DISTINCT FROM occurrence_record.id
       OR NEW.schedule_item_id IS DISTINCT FROM occurrence_record.schedule_item_id
       OR NEW.one_off_lesson_id IS DISTINCT FROM occurrence_record.one_off_lesson_id
       OR NEW.assignment_id IS DISTINCT FROM occurrence_record.assignment_id
       OR NEW.group_id IS DISTINCT FROM occurrence_record.group_id
       OR NEW.subject_id IS DISTINCT FROM occurrence_record.subject_id
       OR NEW.semester_id IS DISTINCT FROM occurrence_record.semester_id
       OR NEW.assigned_teacher_id IS DISTINCT FROM occurrence_record.assigned_teacher_id
       OR NEW.lesson_type IS DISTINCT FROM occurrence_record.lesson_type THEN
        RAISE EXCEPTION 'physical lesson identity snapshot does not match its occurrence';
    END IF;

    IF TG_OP = 'UPDATE'
       AND (NEW.id IS DISTINCT FROM OLD.id
            OR NEW.schedule_item_id IS DISTINCT FROM OLD.schedule_item_id
            OR NEW.one_off_lesson_id IS DISTINCT FROM OLD.one_off_lesson_id
            OR NEW.occurrence_id IS DISTINCT FROM OLD.occurrence_id
            OR NEW.assignment_id IS DISTINCT FROM OLD.assignment_id
            OR NEW.group_id IS DISTINCT FROM OLD.group_id
            OR NEW.subject_id IS DISTINCT FROM OLD.subject_id
            OR NEW.semester_id IS DISTINCT FROM OLD.semester_id
            OR NEW.assigned_teacher_id IS DISTINCT FROM OLD.assigned_teacher_id
            OR NEW.lesson_type IS DISTINCT FROM OLD.lesson_type
            OR NEW.date IS DISTINCT FROM OLD.date
            OR NEW.lesson_number IS DISTINCT FROM OLD.lesson_number
            OR NEW.day_of_week IS DISTINCT FROM OLD.day_of_week
            OR NEW.start_time IS DISTINCT FROM OLD.start_time
            OR NEW.end_time IS DISTINCT FROM OLD.end_time
            OR NEW.room_snapshot IS DISTINCT FROM OLD.room_snapshot
            OR NEW.week_type_snapshot IS DISTINCT FROM OLD.week_type_snapshot
            OR NEW.generation IS DISTINCT FROM OLD.generation) THEN
        RAISE EXCEPTION 'physical lesson identity snapshot is immutable';
    END IF;
    IF TG_OP = 'UPDATE' AND NEW.revision < OLD.revision THEN
        RAISE EXCEPTION 'physical lesson revision cannot move backwards';
    END IF;
    RETURN NEW;
END
$$;

DROP TRIGGER IF EXISTS lessons_history_guard_trg ON lessons;
CREATE TRIGGER lessons_physical_insert_fence_guard_trg
    BEFORE INSERT ON lessons
    FOR EACH ROW
    EXECUTE FUNCTION validate_lesson_insert_fence();
CREATE TRIGGER lessons_history_guard_trg
    BEFORE INSERT OR UPDATE OR DELETE ON lessons
    FOR EACH ROW
    EXECUTE FUNCTION validate_lesson_physical_snapshot();
