server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowed-origins:
              - "http://localhost:5173"
              - "http://localhost:80"
            allowed-methods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
              - OPTIONS
            allowed-headers: "*"
            allow-credentials: true
            max-age: 3600
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      routes:
        - id: auth-service
          uri: http://auth-service:9090
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=1

        - id: academic-service
          uri: http://academic-service:9091
          predicates:
            - Path=/api/academic/**
          filters:
            - StripPrefix=1

        - id: schedule-service
          uri: http://schedule-service:9092
          predicates:
            - Path=/api/schedule/**
          filters:
            - StripPrefix=1

        - id: attendance-service
          uri: http://attendance-service:9093
          predicates:
            - Path=/api/attendance/**
          filters:
            - StripPrefix=1

        - id: notification-web
          uri: http://notification-web:9094
          predicates:
            - Path=/api/ws/**
          filters:
            - StripPrefix=1

        - id: notification-push
          uri: http://notification-web:9094
          predicates:
            - Path=/api/push/**
          filters:
            - StripPrefix=1

gateway:
  auth-service-url: ${AUTH_SERVICE_URL:http://auth-service:9090}

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    ru.rutcampustrack: DEBUG
