# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from bot.grpc_client import attendance_pb2 as bot_dot_grpc__client_dot_attendance__pb2

GRPC_GENERATED_VERSION = '1.73.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in bot/grpc_client/attendance_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AttendanceStudentGrpcServiceStub(object):
    """Internal JS-STUDENT-01-r1 boundary. Identity is a validated signed internal JWT
    in gRPC metadata; client-supplied identity fields are deliberately absent.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetStudentAttendanceSnapshot = channel.unary_unary(
                '/rutcampustrack.attendance.AttendanceStudentGrpcService/GetStudentAttendanceSnapshot',
                request_serializer=bot_dot_grpc__client_dot_attendance__pb2.StudentAttendanceSnapshotRequest.SerializeToString,
                response_deserializer=bot_dot_grpc__client_dot_attendance__pb2.StudentAttendanceSnapshotResponse.FromString,
                _registered_method=True)
        self.Checkin = channel.unary_unary(
                '/rutcampustrack.attendance.AttendanceStudentGrpcService/Checkin',
                request_serializer=bot_dot_grpc__client_dot_attendance__pb2.StudentCheckinCommand.SerializeToString,
                response_deserializer=bot_dot_grpc__client_dot_attendance__pb2.StudentCheckinResult.FromString,
                _registered_method=True)
        self.ListStudentRequests = channel.unary_unary(
                '/rutcampustrack.attendance.AttendanceStudentGrpcService/ListStudentRequests',
                request_serializer=bot_dot_grpc__client_dot_attendance__pb2.StudentRequestListQuery.SerializeToString,
                response_deserializer=bot_dot_grpc__client_dot_attendance__pb2.StudentRequestPage.FromString,
                _registered_method=True)
        self.GetStudentRequest = channel.unary_unary(
                '/rutcampustrack.attendance.AttendanceStudentGrpcService/GetStudentRequest',
                request_serializer=bot_dot_grpc__client_dot_attendance__pb2.StudentRequestId.SerializeToString,
                response_deserializer=bot_dot_grpc__client_dot_attendance__pb2.StudentRequestDetail.FromString,
                _registered_method=True)
        self.GetStudentRequestOptions = channel.unary_unary(
                '/rutcampustrack.attendance.AttendanceStudentGrpcService/GetStudentRequestOptions',
                request_serializer=bot_dot_grpc__client_dot_attendance__pb2.StudentRequestOptionsQuery.SerializeToString,
                response_deserializer=bot_dot_grpc__client_dot_attendance__pb2.StudentRequestOptions.FromString,
                _registered_method=True)
        self.SubmitStudentExcuse = channel.unary_unary(
                '/rutcampustrack.attendance.AttendanceStudentGrpcService/SubmitStudentExcuse',
                request_serializer=bot_dot_grpc__client_dot_attendance__pb2.SubmitStudentExcuseCommand.SerializeToString,
                response_deserializer=bot_dot_grpc__client_dot_attendance__pb2.StudentRequestDetail.FromString,
                _registered_method=True)
        self.SubmitStudentLateCheckin = channel.unary_unary(
                '/rutcampustrack.attendance.AttendanceStudentGrpcService/SubmitStudentLateCheckin',
                request_serializer=bot_dot_grpc__client_dot_attendance__pb2.SubmitStudentLateCheckinCommand.SerializeToString,
                response_deserializer=bot_dot_grpc__client_dot_attendance__pb2.StudentRequestDetail.FromString,
                _registered_method=True)
        self.CancelStudentRequest = channel.unary_unary(
                '/rutcampustrack.attendance.AttendanceStudentGrpcService/CancelStudentRequest',
                request_serializer=bot_dot_grpc__client_dot_attendance__pb2.StudentRequestId.SerializeToString,
                response_deserializer=bot_dot_grpc__client_dot_attendance__pb2.StudentRequestDetail.FromString,
                _registered_method=True)
        self.DownloadStudentRequestAttachment = channel.unary_unary(
                '/rutcampustrack.attendance.AttendanceStudentGrpcService/DownloadStudentRequestAttachment',
                request_serializer=bot_dot_grpc__client_dot_attendance__pb2.StudentRequestAttachmentId.SerializeToString,
                response_deserializer=bot_dot_grpc__client_dot_attendance__pb2.StudentRequestAttachmentDownload.FromString,
                _registered_method=True)


class AttendanceStudentGrpcServiceServicer(object):
    """Internal JS-STUDENT-01-r1 boundary. Identity is a validated signed internal JWT
    in gRPC metadata; client-supplied identity fields are deliberately absent.
    """

    def GetStudentAttendanceSnapshot(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Checkin(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListStudentRequests(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStudentRequest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStudentRequestOptions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitStudentExcuse(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitStudentLateCheckin(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelStudentRequest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DownloadStudentRequestAttachment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AttendanceStudentGrpcServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetStudentAttendanceSnapshot': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStudentAttendanceSnapshot,
                    request_deserializer=bot_dot_grpc__client_dot_attendance__pb2.StudentAttendanceSnapshotRequest.FromString,
                    response_serializer=bot_dot_grpc__client_dot_attendance__pb2.StudentAttendanceSnapshotResponse.SerializeToString,
            ),
            'Checkin': grpc.unary_unary_rpc_method_handler(
                    servicer.Checkin,
                    request_deserializer=bot_dot_grpc__client_dot_attendance__pb2.StudentCheckinCommand.FromString,
                    response_serializer=bot_dot_grpc__client_dot_attendance__pb2.StudentCheckinResult.SerializeToString,
            ),
            'ListStudentRequests': grpc.unary_unary_rpc_method_handler(
                    servicer.ListStudentRequests,
                    request_deserializer=bot_dot_grpc__client_dot_attendance__pb2.StudentRequestListQuery.FromString,
                    response_serializer=bot_dot_grpc__client_dot_attendance__pb2.StudentRequestPage.SerializeToString,
            ),
            'GetStudentRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStudentRequest,
                    request_deserializer=bot_dot_grpc__client_dot_attendance__pb2.StudentRequestId.FromString,
                    response_serializer=bot_dot_grpc__client_dot_attendance__pb2.StudentRequestDetail.SerializeToString,
            ),
            'GetStudentRequestOptions': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStudentRequestOptions,
                    request_deserializer=bot_dot_grpc__client_dot_attendance__pb2.StudentRequestOptionsQuery.FromString,
                    response_serializer=bot_dot_grpc__client_dot_attendance__pb2.StudentRequestOptions.SerializeToString,
            ),
            'SubmitStudentExcuse': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitStudentExcuse,
                    request_deserializer=bot_dot_grpc__client_dot_attendance__pb2.SubmitStudentExcuseCommand.FromString,
                    response_serializer=bot_dot_grpc__client_dot_attendance__pb2.StudentRequestDetail.SerializeToString,
            ),
            'SubmitStudentLateCheckin': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitStudentLateCheckin,
                    request_deserializer=bot_dot_grpc__client_dot_attendance__pb2.SubmitStudentLateCheckinCommand.FromString,
                    response_serializer=bot_dot_grpc__client_dot_attendance__pb2.StudentRequestDetail.SerializeToString,
            ),
            'CancelStudentRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelStudentRequest,
                    request_deserializer=bot_dot_grpc__client_dot_attendance__pb2.StudentRequestId.FromString,
                    response_serializer=bot_dot_grpc__client_dot_attendance__pb2.StudentRequestDetail.SerializeToString,
            ),
            'DownloadStudentRequestAttachment': grpc.unary_unary_rpc_method_handler(
                    servicer.DownloadStudentRequestAttachment,
                    request_deserializer=bot_dot_grpc__client_dot_attendance__pb2.StudentRequestAttachmentId.FromString,
                    response_serializer=bot_dot_grpc__client_dot_attendance__pb2.StudentRequestAttachmentDownload.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'rutcampustrack.attendance.AttendanceStudentGrpcService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('rutcampustrack.attendance.AttendanceStudentGrpcService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AttendanceStudentGrpcService(object):
    """Internal JS-STUDENT-01-r1 boundary. Identity is a validated signed internal JWT
    in gRPC metadata; client-supplied identity fields are deliberately absent.
    """

    @staticmethod
    def GetStudentAttendanceSnapshot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rutcampustrack.attendance.AttendanceStudentGrpcService/GetStudentAttendanceSnapshot',
            bot_dot_grpc__client_dot_attendance__pb2.StudentAttendanceSnapshotRequest.SerializeToString,
            bot_dot_grpc__client_dot_attendance__pb2.StudentAttendanceSnapshotResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Checkin(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rutcampustrack.attendance.AttendanceStudentGrpcService/Checkin',
            bot_dot_grpc__client_dot_attendance__pb2.StudentCheckinCommand.SerializeToString,
            bot_dot_grpc__client_dot_attendance__pb2.StudentCheckinResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListStudentRequests(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rutcampustrack.attendance.AttendanceStudentGrpcService/ListStudentRequests',
            bot_dot_grpc__client_dot_attendance__pb2.StudentRequestListQuery.SerializeToString,
            bot_dot_grpc__client_dot_attendance__pb2.StudentRequestPage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStudentRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rutcampustrack.attendance.AttendanceStudentGrpcService/GetStudentRequest',
            bot_dot_grpc__client_dot_attendance__pb2.StudentRequestId.SerializeToString,
            bot_dot_grpc__client_dot_attendance__pb2.StudentRequestDetail.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStudentRequestOptions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rutcampustrack.attendance.AttendanceStudentGrpcService/GetStudentRequestOptions',
            bot_dot_grpc__client_dot_attendance__pb2.StudentRequestOptionsQuery.SerializeToString,
            bot_dot_grpc__client_dot_attendance__pb2.StudentRequestOptions.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitStudentExcuse(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rutcampustrack.attendance.AttendanceStudentGrpcService/SubmitStudentExcuse',
            bot_dot_grpc__client_dot_attendance__pb2.SubmitStudentExcuseCommand.SerializeToString,
            bot_dot_grpc__client_dot_attendance__pb2.StudentRequestDetail.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitStudentLateCheckin(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rutcampustrack.attendance.AttendanceStudentGrpcService/SubmitStudentLateCheckin',
            bot_dot_grpc__client_dot_attendance__pb2.SubmitStudentLateCheckinCommand.SerializeToString,
            bot_dot_grpc__client_dot_attendance__pb2.StudentRequestDetail.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelStudentRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rutcampustrack.attendance.AttendanceStudentGrpcService/CancelStudentRequest',
            bot_dot_grpc__client_dot_attendance__pb2.StudentRequestId.SerializeToString,
            bot_dot_grpc__client_dot_attendance__pb2.StudentRequestDetail.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DownloadStudentRequestAttachment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rutcampustrack.attendance.AttendanceStudentGrpcService/DownloadStudentRequestAttachment',
            bot_dot_grpc__client_dot_attendance__pb2.StudentRequestAttachmentId.SerializeToString,
            bot_dot_grpc__client_dot_attendance__pb2.StudentRequestAttachmentDownload.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class AttendanceRequestBotGrpcServiceStub(object):
    """Separate service for notification-bot attachment reads. It has its own
    x-grpc-secret interceptor; public student JWT protection never applies here.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.FetchExcuseAttachment = channel.unary_unary(
                '/rutcampustrack.attendance.AttendanceRequestBotGrpcService/FetchExcuseAttachment',
                request_serializer=bot_dot_grpc__client_dot_attendance__pb2.FetchExcuseAttachmentRequest.SerializeToString,
                response_deserializer=bot_dot_grpc__client_dot_attendance__pb2.FetchExcuseAttachmentResponse.FromString,
                _registered_method=True)
        self.ResolveRequestNotification = channel.unary_unary(
                '/rutcampustrack.attendance.AttendanceRequestBotGrpcService/ResolveRequestNotification',
                request_serializer=bot_dot_grpc__client_dot_attendance__pb2.ResolveRequestNotificationRequest.SerializeToString,
                response_deserializer=bot_dot_grpc__client_dot_attendance__pb2.ResolveRequestNotificationResponse.FromString,
                _registered_method=True)


class AttendanceRequestBotGrpcServiceServicer(object):
    """Separate service for notification-bot attachment reads. It has its own
    x-grpc-secret interceptor; public student JWT protection never applies here.
    """

    def FetchExcuseAttachment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResolveRequestNotification(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AttendanceRequestBotGrpcServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'FetchExcuseAttachment': grpc.unary_unary_rpc_method_handler(
                    servicer.FetchExcuseAttachment,
                    request_deserializer=bot_dot_grpc__client_dot_attendance__pb2.FetchExcuseAttachmentRequest.FromString,
                    response_serializer=bot_dot_grpc__client_dot_attendance__pb2.FetchExcuseAttachmentResponse.SerializeToString,
            ),
            'ResolveRequestNotification': grpc.unary_unary_rpc_method_handler(
                    servicer.ResolveRequestNotification,
                    request_deserializer=bot_dot_grpc__client_dot_attendance__pb2.ResolveRequestNotificationRequest.FromString,
                    response_serializer=bot_dot_grpc__client_dot_attendance__pb2.ResolveRequestNotificationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'rutcampustrack.attendance.AttendanceRequestBotGrpcService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('rutcampustrack.attendance.AttendanceRequestBotGrpcService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AttendanceRequestBotGrpcService(object):
    """Separate service for notification-bot attachment reads. It has its own
    x-grpc-secret interceptor; public student JWT protection never applies here.
    """

    @staticmethod
    def FetchExcuseAttachment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rutcampustrack.attendance.AttendanceRequestBotGrpcService/FetchExcuseAttachment',
            bot_dot_grpc__client_dot_attendance__pb2.FetchExcuseAttachmentRequest.SerializeToString,
            bot_dot_grpc__client_dot_attendance__pb2.FetchExcuseAttachmentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResolveRequestNotification(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rutcampustrack.attendance.AttendanceRequestBotGrpcService/ResolveRequestNotification',
            bot_dot_grpc__client_dot_attendance__pb2.ResolveRequestNotificationRequest.SerializeToString,
            bot_dot_grpc__client_dot_attendance__pb2.ResolveRequestNotificationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
