{
 "title": "Docker and system monitoring",
 "description": "A simple overview of the most important Docker host and container metrics. (cAdvisor/Prometheus)",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "30s,1m,5m,10m,30m,1h,6h,1d" }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - node_boot_time_seconds"
    }
   ]
  },
  {
   "title": "Containers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(label_replace(container_last_seen{name=~\".+\"}, \"container_name\", \"$1\", \"name\", \"(.+)\") or label_replace(container_last_seen{name=\"\", container_label_com_docker_compose_service=~\".+\"}, \"container_name\", \"$1\", \"container_label_com_docker_compose_service\", \"(.+)\"))"
    }
   ]
  },
  {
   "title": "Disk space",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min((node_filesystem_size_bytes{fstype=~\"xfs|ext4\"} - node_filesystem_free_bytes{fstype=~\"xfs|ext4\"}) / node_filesystem_size_bytes{fstype=~\"xfs|ext4\"})"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes) * 100"
    }
   ]
  },
  {
   "title": "Swap",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_SwapTotal_bytes - node_memory_SwapFree_bytes"
    }
   ]
  },
  {
   "title": "Load",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "node_load1 / count without(cpu, mode)(node_cpu_seconds_total{mode=\"idle\"})"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{id=\"/\"}[$interval])) by (id)",
     "legendFormat": "RECEIVED"
    },
    {
     "expr": "- sum(rate(container_network_transmit_bytes_total{id=\"/\"}[$interval])) by (id)",
     "legendFormat": "SENT"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(process_cpu_seconds_total[$interval])) * 100",
     "legendFormat": "host"
    }
   ]
  },
  {
   "title": "Load",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "node_load1 / count without(cpu, mode)(node_cpu_seconds_total{mode=\"idle\"})"
    }
   ]
  },
  {
   "title": "Used Disk Space",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{fstype=~\"xfs|ext4\"} - node_filesystem_free_bytes{fstype=~\"xfs|ext4\"}",
     "legendFormat": "Used Disk Space"
    }
   ]
  },
  {
   "title": "Used Memory",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes",
     "legendFormat": "Used Memory"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "-sum(rate(node_disk_read_bytes_total[$interval])) by (device)",
     "legendFormat": "OUT on /{{device}}"
    },
    {
     "expr": "sum(rate(node_disk_written_bytes_total[$interval])) by (device)",
     "legendFormat": "IN on /{{device}}"
    }
   ]
  },
  {
   "title": "Received Network Traffic per Container",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (container_name) (label_replace(rate(container_network_receive_bytes_total{name=~\".+\"}[$interval]), \"container_name\", \"$1\", \"name\", \"(.+)\") or label_replace(rate(container_network_receive_bytes_total{name=\"\", container_label_com_docker_compose_service=~\".+\"}[$interval]), \"container_name\", \"$1\", \"container_label_com_docker_compose_service\", \"(.+)\"))",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "Sent Network Traffic per Container",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (container_name) (label_replace(rate(container_network_transmit_bytes_total{name=~\".+\"}[$interval]), \"container_name\", \"$1\", \"name\", \"(.+)\") or label_replace(rate(container_network_transmit_bytes_total{name=\"\", container_label_com_docker_compose_service=~\".+\"}[$interval]), \"container_name\", \"$1\", \"container_label_com_docker_compose_service\", \"(.+)\"))",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "CPU Usage per Container",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (container_name) (label_replace(rate(container_cpu_usage_seconds_total{name=~\".+\"}[$interval]), \"container_name\", \"$1\", \"name\", \"(.+)\") or label_replace(rate(container_cpu_usage_seconds_total{name=\"\", container_label_com_docker_compose_service=~\".+\"}[$interval]), \"container_name\", \"$1\", \"container_label_com_docker_compose_service\", \"(.+)\")) * 100",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "Memory Swap per Container",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (container_name) (label_replace(container_memory_swap{name=~\".+\"}, \"container_name\", \"$1\", \"name\", \"(.+)\") or label_replace(container_memory_swap{name=\"\", container_label_com_docker_compose_service=~\".+\"}, \"container_name\", \"$1\", \"container_label_com_docker_compose_service\", \"(.+)\"))",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "Memory Usage per Container",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (container_name) (label_replace(container_memory_working_set_bytes{name=~\".+\"}, \"container_name\", \"$1\", \"name\", \"(.+)\") or label_replace(container_memory_working_set_bytes{name=\"\", container_label_com_docker_compose_service=~\".+\"}, \"container_name\", \"$1\", \"container_label_com_docker_compose_service\", \"(.+)\"))",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "Limit memory",
   "type": "table",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (container_name) (label_replace(container_spec_memory_limit_bytes{name=~\".+\"}, \"container_name\", \"$1\", \"name\", \"(.+)\") or label_replace(container_spec_memory_limit_bytes{name=\"\", container_label_com_docker_compose_service=~\".+\"}, \"container_name\", \"$1\", \"container_label_com_docker_compose_service\", \"(.+)\"))",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "Usage memory",
   "type": "table",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (container_name) (label_replace(container_memory_usage_bytes{name=~\".+\"}, \"container_name\", \"$1\", \"name\", \"(.+)\") or label_replace(container_memory_usage_bytes{name=\"\", container_label_com_docker_compose_service=~\".+\"}, \"container_name\", \"$1\", \"container_label_com_docker_compose_service\", \"(.+)\"))",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "Remaining memory",
   "type": "table",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * sum by (container_name) (label_replace(container_memory_usage_bytes{name=~\".+\"}, \"container_name\", \"$1\", \"name\", \"(.+)\") or label_replace(container_memory_usage_bytes{name=\"\", container_label_com_docker_compose_service=~\".+\"}, \"container_name\", \"$1\", \"container_label_com_docker_compose_service\", \"(.+)\")) / sum by (container_name) (label_replace(container_spec_memory_limit_bytes{name=~\".+\"}, \"container_name\", \"$1\", \"name\", \"(.+)\") or label_replace(container_spec_memory_limit_bytes{name=\"\", container_label_com_docker_compose_service=~\".+\"}, \"container_name\", \"$1\", \"container_label_com_docker_compose_service\", \"(.+)\"))",
     "legendFormat": "{{container_name}}"
    }
   ]
  }
 ]
}