-- B0 foundation: durable session, role-grant and account-security authority.
-- Legacy role/status/headman columns remain until the coordinated B1 reader cutover.
-- Flyway owns the transaction so a failed preflight or DDL statement rolls back
-- both schema objects and the Flyway history row.

DO $$
BEGIN
    -- The enum columns already restrict the normal values. Keep this explicit
    -- source gate so a future legacy representation cannot be guessed into the
    -- new authority tables.
    IF EXISTS (
        SELECT 1
        FROM users
        WHERE role::text NOT IN ('admin', 'teacher', 'student')
           OR status::text NOT IN ('active', 'expelled', 'suspended', 'archived')
    ) THEN
        RAISE EXCEPTION 'V24 cannot convert an unknown legacy role or status';
    END IF;

    IF EXISTS (
        SELECT 1
        FROM users
        WHERE is_headman
          AND (role::text <> 'student' OR group_id IS NULL)
    ) THEN
        RAISE EXCEPTION 'V24 cannot convert an inconsistent legacy headman row';
    END IF;
END
$$;

ALTER TABLE users
    ADD COLUMN roles_version BIGINT NOT NULL DEFAULT 1;

ALTER TABLE users
    ADD CONSTRAINT users_roles_version_positive
        CHECK (roles_version > 0);

CREATE TABLE user_role_grants
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT      NOT NULL,
    role        VARCHAR(16) NOT NULL,
    status      VARCHAR(16) NOT NULL,
    group_id    BIGINT,
    created_at  TIMESTAMPTZ NOT NULL,
    updated_at  TIMESTAMPTZ NOT NULL,

    CONSTRAINT user_role_grants_user_fk
        FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT user_role_grants_group_fk
        FOREIGN KEY (group_id) REFERENCES groups (id) ON DELETE RESTRICT,
    CONSTRAINT user_role_grants_role_chk
        CHECK (role IN ('student', 'headman', 'teacher', 'admin')),
    CONSTRAINT user_role_grants_status_chk
        CHECK (status IN ('active', 'expelled', 'graduated', 'suspended', 'archived')),
    CONSTRAINT user_role_grants_headman_group_chk
        CHECK (role <> 'headman' OR group_id IS NOT NULL),
    CONSTRAINT user_role_grants_id_user_uq
        UNIQUE (id, user_id),
    CONSTRAINT user_role_grants_user_role_uq
        UNIQUE (user_id, role)
);

-- Only facts represented by the legacy row are copied. Redis tokens and
-- inferred grants have no durable source in this migration.
INSERT INTO user_role_grants (user_id, role, status, group_id, created_at, updated_at)
SELECT id, role::text, status::text, group_id, created_at, updated_at
FROM users;

INSERT INTO user_role_grants (user_id, role, status, group_id, created_at, updated_at)
SELECT id, 'headman', status::text, group_id, created_at, updated_at
FROM users
WHERE role::text = 'student'
  AND is_headman;

CREATE INDEX idx_user_role_grants_active_student_group
    ON user_role_grants (group_id, user_id)
    WHERE role = 'student' AND status = 'active';

CREATE OR REPLACE FUNCTION bump_user_roles_version()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    IF TG_OP = 'UPDATE' AND NEW.user_id IS DISTINCT FROM OLD.user_id THEN
        RAISE EXCEPTION 'user_role_grants.user_id is immutable';
    END IF;

    IF TG_OP = 'INSERT' THEN
        UPDATE users
        SET roles_version = roles_version + 1,
            updated_at = updated_at
        WHERE id = NEW.user_id;
        RETURN NEW;
    END IF;

    IF TG_OP = 'DELETE' THEN
        UPDATE users
        SET roles_version = roles_version + 1,
            updated_at = updated_at
        WHERE id = OLD.user_id;
        RETURN OLD;
    END IF;

    IF NEW.role IS DISTINCT FROM OLD.role
       OR NEW.status IS DISTINCT FROM OLD.status
       OR NEW.group_id IS DISTINCT FROM OLD.group_id THEN
        UPDATE users
        SET roles_version = roles_version + 1,
            updated_at = updated_at
        WHERE id = NEW.user_id;
    END IF;
    RETURN NEW;
END
$$;

CREATE TRIGGER user_role_grants_roles_version_trg
    AFTER INSERT OR UPDATE OR DELETE ON user_role_grants
    FOR EACH ROW
    EXECUTE FUNCTION bump_user_roles_version();

CREATE TABLE auth_sessions
(
    sid                    UUID         PRIMARY KEY,
    user_id                BIGINT       NOT NULL,
    active_role_grant_id   BIGINT,
    session_version        BIGINT       NOT NULL,
    current_refresh_jti    UUID         NOT NULL UNIQUE,
    previous_refresh_jti   UUID,
    refresh_expires_at     TIMESTAMPTZ  NOT NULL,
    created_at              TIMESTAMPTZ  NOT NULL,
    last_seen_at            TIMESTAMPTZ  NOT NULL,
    revoked_at             TIMESTAMPTZ,
    revoke_reason          VARCHAR(32),
    auth_method            VARCHAR(16)  NOT NULL,
    client_label           VARCHAR(160),
    location_label         VARCHAR(160),

    CONSTRAINT auth_sessions_user_fk
        FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT auth_sessions_active_grant_fk
        FOREIGN KEY (active_role_grant_id, user_id)
        REFERENCES user_role_grants (id, user_id) ON DELETE RESTRICT,
    CONSTRAINT auth_sessions_id_user_uq
        UNIQUE (sid, user_id),
    CONSTRAINT auth_sessions_version_positive_chk
        CHECK (session_version > 0),
    CONSTRAINT auth_sessions_refresh_rotation_chk
        CHECK (previous_refresh_jti IS NULL OR previous_refresh_jti <> current_refresh_jti),
    CONSTRAINT auth_sessions_expiry_chk
        CHECK (refresh_expires_at > created_at),
    CONSTRAINT auth_sessions_last_seen_chk
        CHECK (last_seen_at >= created_at),
    CONSTRAINT auth_sessions_revocation_pair_chk
        CHECK ((revoked_at IS NULL AND revoke_reason IS NULL)
            OR (revoked_at IS NOT NULL AND revoke_reason IS NOT NULL)),
    CONSTRAINT auth_sessions_revoke_reason_chk
        CHECK (revoke_reason IS NULL OR revoke_reason IN
               ('CURRENT_LOGOUT', 'LOGOUT_ALL', 'PASSWORD_CHANGED', 'SECURITY_REVOKED')),
    CONSTRAINT auth_sessions_method_chk
        CHECK (auth_method IN ('PASSWORD', 'OTP', 'TMA'))
);

CREATE INDEX idx_auth_sessions_live_user_created
    ON auth_sessions (user_id, created_at DESC, sid DESC)
    WHERE revoked_at IS NULL;

CREATE TABLE account_security_events
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id           BIGINT       NOT NULL,
    sid               UUID,
    event_type        VARCHAR(32)  NOT NULL,
    occurred_at       TIMESTAMPTZ  NOT NULL,
    auth_method       VARCHAR(16),
    client_label      VARCHAR(160),
    location_label    VARCHAR(160),

    CONSTRAINT account_security_events_user_fk
        FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT account_security_events_sid_user_fk
        FOREIGN KEY (sid, user_id)
        REFERENCES auth_sessions (sid, user_id) ON DELETE RESTRICT,
    CONSTRAINT account_security_events_type_chk
        CHECK (event_type IN
               ('LOGIN', 'ROLE_CHANGED', 'CURRENT_LOGOUT', 'LOGOUT_ALL',
                'PASSWORD_CHANGED', 'SECURITY_REVOKED')),
    CONSTRAINT account_security_events_method_chk
        CHECK (auth_method IS NULL OR auth_method IN ('PASSWORD', 'OTP', 'TMA'))
);

CREATE INDEX idx_account_security_events_user_time
    ON account_security_events (user_id, occurred_at DESC, id DESC);

CREATE OR REPLACE FUNCTION reject_account_security_event_mutation()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    RAISE EXCEPTION 'account_security_events is append-only';
END
$$;

CREATE TRIGGER account_security_events_append_only_trg
    BEFORE UPDATE OR DELETE ON account_security_events
    FOR EACH ROW
    EXECUTE FUNCTION reject_account_security_event_mutation();
