-- B0 foundation: subject lesson types, effective-dated assignments and the
-- academic half of a reserved homework binding.
-- Flyway owns the transaction; the source gate is deliberately before DDL.

DO $$
BEGIN
    -- teacher_subject_groups is the former assignment shape. It has no
    -- validity/type provenance, so no row can be safely inferred.
    IF EXISTS (SELECT 1 FROM teacher_subject_groups) THEN
        RAISE EXCEPTION
            'V25 cannot migrate legacy teacher_subject_groups without validity provenance';
    END IF;
    IF EXISTS (SELECT 1 FROM homeworks) THEN
        RAISE EXCEPTION
            'V25 cannot migrate legacy homeworks without a durable binding';
    END IF;
END
$$;

CREATE EXTENSION IF NOT EXISTS btree_gist;

CREATE TABLE subject_lesson_types
(
    subject_id  BIGINT      NOT NULL,
    lesson_type subject_type NOT NULL,

    CONSTRAINT subject_lesson_types_pk
        PRIMARY KEY (subject_id, lesson_type),
    CONSTRAINT subject_lesson_types_subject_fk
        FOREIGN KEY (subject_id) REFERENCES subjects (id) ON DELETE RESTRICT,
    CONSTRAINT subject_lesson_types_type_chk
        CHECK (lesson_type IN ('lecture', 'practice', 'lab'))
);

-- Seed only the explicit legacy subject.type value. Names, groups and schedule
-- rows are not provenance for an additional type.
INSERT INTO subject_lesson_types (subject_id, lesson_type)
SELECT id, type
FROM subjects;

ALTER TABLE subjects
    ADD CONSTRAINT subjects_id_group_uq UNIQUE (id, group_id);

CREATE OR REPLACE FUNCTION enforce_subject_lesson_type_parent()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    affected_subject_id BIGINT;
BEGIN
    affected_subject_id := CASE WHEN TG_OP = 'DELETE' THEN OLD.id ELSE NEW.id END;

    -- A row lock on the parent serializes concurrent deferred checks for the
    -- same subject. Two transactions deleting different types cannot both pass
    -- the final EXISTS check and leave a subject with zero types.
    PERFORM 1
    FROM subjects
    WHERE id = affected_subject_id
    FOR UPDATE;

    IF FOUND AND NOT EXISTS (
        SELECT 1
        FROM subject_lesson_types
        WHERE subject_id = affected_subject_id
    ) THEN
        RAISE EXCEPTION 'subject % must retain at least one lesson type', affected_subject_id;
    END IF;
    RETURN CASE WHEN TG_OP = 'DELETE' THEN OLD ELSE NEW END;
END
$$;

CREATE OR REPLACE FUNCTION enforce_subject_lesson_type_child()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    affected_subject_id BIGINT;
BEGIN
    affected_subject_id := CASE
        WHEN TG_OP = 'DELETE' THEN OLD.subject_id
        ELSE NEW.subject_id
    END;

    PERFORM 1
    FROM subjects
    WHERE id = affected_subject_id
    FOR UPDATE;

    IF FOUND AND NOT EXISTS (
        SELECT 1
        FROM subject_lesson_types
        WHERE subject_id = affected_subject_id
    ) THEN
        RAISE EXCEPTION 'subject % must retain at least one lesson type', affected_subject_id;
    END IF;
    RETURN CASE WHEN TG_OP = 'DELETE' THEN OLD ELSE NEW END;
END
$$;

CREATE OR REPLACE FUNCTION protect_subject_lesson_type_subject()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    IF NEW.subject_id IS DISTINCT FROM OLD.subject_id THEN
        RAISE EXCEPTION 'subject_lesson_types.subject_id is immutable';
    END IF;
    RETURN NEW;
END
$$;

CREATE CONSTRAINT TRIGGER subjects_lesson_type_minimum_trg
    AFTER INSERT OR UPDATE ON subjects
    DEFERRABLE INITIALLY DEFERRED
    FOR EACH ROW
    EXECUTE FUNCTION enforce_subject_lesson_type_parent();

CREATE CONSTRAINT TRIGGER subject_lesson_types_minimum_trg
    AFTER INSERT OR UPDATE OR DELETE ON subject_lesson_types
    DEFERRABLE INITIALLY DEFERRED
    FOR EACH ROW
    EXECUTE FUNCTION enforce_subject_lesson_type_child();

CREATE TRIGGER subject_lesson_types_subject_guard_trg
    BEFORE UPDATE ON subject_lesson_types
    FOR EACH ROW
    EXECUTE FUNCTION protect_subject_lesson_type_subject();

CREATE TABLE assignments
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    teacher_id              BIGINT       NOT NULL,
    subject_id              BIGINT       NOT NULL,
    group_id                BIGINT       NOT NULL,
    semester_id             BIGINT       NOT NULL,
    lesson_type             subject_type NOT NULL,
    valid_from              DATE         NOT NULL,
    valid_until_exclusive   DATE,
    created_at              TIMESTAMPTZ  NOT NULL DEFAULT NOW(),

    CONSTRAINT assignments_id_positive_chk
        CHECK (id > 0),
    CONSTRAINT assignments_teacher_fk
        FOREIGN KEY (teacher_id) REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT assignments_subject_group_fk
        FOREIGN KEY (subject_id, group_id)
        REFERENCES subjects (id, group_id) ON DELETE RESTRICT,
    CONSTRAINT assignments_semester_fk
        FOREIGN KEY (semester_id) REFERENCES semesters (id) ON DELETE RESTRICT,
    CONSTRAINT assignments_subject_type_fk
        FOREIGN KEY (subject_id, lesson_type)
        REFERENCES subject_lesson_types (subject_id, lesson_type) ON DELETE RESTRICT,
    CONSTRAINT assignments_validity_chk
        CHECK (valid_until_exclusive IS NULL OR valid_until_exclusive > valid_from),
    CONSTRAINT assignments_identity_uq
        UNIQUE (id, subject_id, group_id, semester_id, lesson_type),
    CONSTRAINT assignments_no_same_teacher_overlap
        EXCLUDE USING gist
        (
            teacher_id WITH =,
            subject_id WITH =,
            group_id WITH =,
            semester_id WITH =,
            lesson_type WITH =,
            daterange(valid_from, valid_until_exclusive, '[)') WITH &&
        )
);

CREATE INDEX idx_assignments_group_semester
    ON assignments (group_id, semester_id, valid_from);

CREATE INDEX idx_assignments_teacher_effective
    ON assignments (teacher_id, semester_id, valid_from);

CREATE OR REPLACE FUNCTION protect_assignment_identity()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'assignments are closed, never deleted';
    END IF;

    IF NEW.id IS DISTINCT FROM OLD.id
       OR NEW.teacher_id IS DISTINCT FROM OLD.teacher_id
       OR NEW.subject_id IS DISTINCT FROM OLD.subject_id
       OR NEW.group_id IS DISTINCT FROM OLD.group_id
       OR NEW.semester_id IS DISTINCT FROM OLD.semester_id
       OR NEW.lesson_type IS DISTINCT FROM OLD.lesson_type
       OR NEW.valid_from IS DISTINCT FROM OLD.valid_from
       OR NEW.created_at IS DISTINCT FROM OLD.created_at THEN
        RAISE EXCEPTION 'assignment identity is immutable';
    END IF;

    IF OLD.valid_until_exclusive IS NOT NULL
       AND (NEW.valid_until_exclusive IS NULL
            OR NEW.valid_until_exclusive > OLD.valid_until_exclusive) THEN
        RAISE EXCEPTION 'closed assignment validity cannot be extended or reopened';
    END IF;
    IF NEW.valid_until_exclusive IS NOT NULL
       AND NEW.valid_until_exclusive <= NEW.valid_from THEN
        RAISE EXCEPTION 'assignment close must be after valid_from';
    END IF;
    RETURN NEW;
END
$$;

CREATE TRIGGER assignments_identity_guard_trg
    BEFORE UPDATE OR DELETE ON assignments
    FOR EACH ROW
    EXECUTE FUNCTION protect_assignment_identity();

-- Academic stores content and the immutable binding identity received from
-- Schedule. Legacy date/number columns remain for the coordinated B1 cutover.
ALTER TABLE homeworks
    ADD COLUMN binding_id       BIGINT      NOT NULL,
    ADD COLUMN actor_id         BIGINT      NOT NULL,
    ADD COLUMN request_key      UUID        NOT NULL,
    ADD COLUMN payload_hash     BYTEA       NOT NULL,
    ADD COLUMN publication_state VARCHAR(16) NOT NULL DEFAULT 'PENDING';

ALTER TABLE homeworks
    ADD CONSTRAINT homeworks_binding_positive_chk
        CHECK (binding_id > 0),
    ADD CONSTRAINT homeworks_actor_fk
        FOREIGN KEY (actor_id) REFERENCES users (id) ON DELETE RESTRICT,
    ADD CONSTRAINT homeworks_payload_hash_chk
        CHECK (octet_length(payload_hash) = 32),
    ADD CONSTRAINT homeworks_publication_state_chk
        CHECK (publication_state IN ('PENDING', 'ACTIVE')),
    ADD CONSTRAINT homeworks_binding_uq
        UNIQUE (binding_id),
    ADD CONSTRAINT homeworks_actor_request_uq
        UNIQUE (actor_id, request_key);

CREATE OR REPLACE FUNCTION protect_homework_binding_identity()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    IF NEW.binding_id IS DISTINCT FROM OLD.binding_id
       OR NEW.actor_id IS DISTINCT FROM OLD.actor_id
       OR NEW.request_key IS DISTINCT FROM OLD.request_key
       OR NEW.payload_hash IS DISTINCT FROM OLD.payload_hash THEN
        RAISE EXCEPTION 'homework binding identity is immutable';
    END IF;
    IF OLD.publication_state = 'ACTIVE' AND NEW.publication_state <> 'ACTIVE' THEN
        RAISE EXCEPTION 'active homework publication cannot be reverted';
    END IF;
    RETURN NEW;
END
$$;

CREATE TRIGGER homeworks_binding_identity_guard_trg
    BEFORE UPDATE ON homeworks
    FOR EACH ROW
    EXECUTE FUNCTION protect_homework_binding_identity();
