ALTER TABLE homeworks ALTER COLUMN lesson_number DROP NOT NULL,
    ADD COLUMN binding_mode VARCHAR(8) NOT NULL DEFAULT 'LESSON',
    ADD COLUMN revision BIGINT NOT NULL DEFAULT 1 CHECK (revision > 0),
    ADD COLUMN create_intent JSONB,
    ADD COLUMN create_intent_kind VARCHAR(32),
    ADD CONSTRAINT homeworks_binding_mode_chk CHECK (
        (binding_mode = 'LESSON' AND lesson_number BETWEEN 1 AND 8)
        OR (binding_mode = 'DATE' AND lesson_number IS NULL)),
    ADD CONSTRAINT homeworks_create_intent_chk CHECK (
        (create_intent IS NULL AND create_intent_kind IS NULL)
        OR (create_intent IS NOT NULL AND create_intent_kind IN ('ORIGINAL_CREATE', 'LEGACY_ACCEPTED_REPLAY')));

CREATE TABLE homework_edit_receipts (
    homework_id BIGINT NOT NULL REFERENCES homeworks(id) ON DELETE CASCADE,
    semester_id BIGINT NOT NULL,
    actor_id BIGINT NOT NULL,
    request_key UUID NOT NULL,
    command_hash BYTEA NOT NULL CHECK (octet_length(command_hash) = 32),
    result_revision BIGINT NOT NULL CHECK (result_revision > 0),
    result_snapshot JSONB NOT NULL,
    PRIMARY KEY (homework_id, actor_id, request_key)
);
CREATE TABLE homework_edit_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    homework_id BIGINT NOT NULL REFERENCES homeworks(id) ON DELETE CASCADE,
    semester_id BIGINT NOT NULL,
    revision BIGINT NOT NULL CHECK (revision > 0),
    actor_id BIGINT NOT NULL,
    occurred_at TIMESTAMPTZ NOT NULL,
    action VARCHAR(32) NOT NULL,
    before_snapshot JSONB NOT NULL,
    after_snapshot JSONB NOT NULL,
    UNIQUE (homework_id, revision)
);
CREATE TABLE homework_edit_operations (
    operation_id UUID PRIMARY KEY,
    homework_id BIGINT NOT NULL REFERENCES homeworks(id) ON DELETE CASCADE,
    binding_id BIGINT NOT NULL,
    actor_id BIGINT NOT NULL,
    request_key UUID NOT NULL,
    command_hash BYTEA NOT NULL CHECK (octet_length(command_hash) = 32),
    group_id BIGINT NOT NULL, subject_id BIGINT NOT NULL, semester_id BIGINT NOT NULL,
    expected_revision BIGINT NOT NULL,
    expected_binding_revision BIGINT NOT NULL,
    request JSONB NOT NULL,
    before_snapshot JSONB NOT NULL,
    desired_snapshot JSONB NOT NULL,
    target_occurrence_id BIGINT,
    target_lesson_revision BIGINT,
    state VARCHAR(16) NOT NULL DEFAULT 'PREPARED' CHECK (state IN ('PREPARED', 'FINALIZED', 'ACKNOWLEDGED', 'CANCELLED')),
    outcome VARCHAR(24) CHECK (outcome IN ('APPLIED', 'TERMINAL_ABORTED', 'NOT_ACCEPTED')),
    result_snapshot JSONB,
    result_revision BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    finalized_at TIMESTAMPTZ,
    attempts INTEGER NOT NULL DEFAULT 0,
    next_attempt_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_failure VARCHAR(80),
    UNIQUE (homework_id, actor_id, request_key),
    CONSTRAINT homework_edit_outcome_consistent CHECK (
        (state = 'PREPARED' AND outcome IS NULL AND result_snapshot IS NULL AND result_revision IS NULL AND finalized_at IS NULL)
        OR (state = 'CANCELLED' AND outcome = 'NOT_ACCEPTED' AND result_snapshot IS NULL AND result_revision IS NULL AND finalized_at IS NOT NULL)
        OR (state IN ('FINALIZED','ACKNOWLEDGED') AND outcome IN ('APPLIED','TERMINAL_ABORTED')
            AND result_snapshot IS NOT NULL AND result_revision > 0 AND finalized_at IS NOT NULL))
);
CREATE UNIQUE INDEX homework_one_pending_edit ON homework_edit_operations(homework_id)
    WHERE state IN ('PREPARED', 'FINALIZED');
CREATE TABLE homework_edit_archive_admissions (
    archive_operation_id UUID NOT NULL,
    state_version BIGINT NOT NULL,
    semester_id BIGINT NOT NULL,
    edit_operation_id UUID NOT NULL REFERENCES homework_edit_operations(operation_id) ON DELETE CASCADE,
    command_hash BYTEA NOT NULL,
    PRIMARY KEY (archive_operation_id, edit_operation_id)
);
ALTER TABLE homework_binding_transfer_markers ADD COLUMN superseded_by_edit_operation_id UUID
    REFERENCES homework_edit_operations(operation_id) ON DELETE RESTRICT;
ALTER TABLE academic_semester_archive_publication_admissions
    DROP CONSTRAINT academic_semester_archive_admission_schedule_identity,
    ADD CONSTRAINT academic_semester_archive_admission_schedule_identity CHECK (
        (schedule_occurrence_id IS NULL AND schedule_revision IS NULL)
        OR (schedule_occurrence_id >= 0 AND schedule_revision > 0));

CREATE OR REPLACE FUNCTION academic_homework_edit_epoch_admitted(edit_id UUID, semester BIGINT)
RETURNS BOOLEAN LANGUAGE SQL STABLE AS $$
    SELECT EXISTS (SELECT 1 FROM homework_edit_archive_admissions a
        JOIN homework_edit_operations e ON e.operation_id = a.edit_operation_id AND e.command_hash = a.command_hash
        JOIN academic_semester_archive_barriers b ON b.semester_id = a.semester_id
          AND b.operation_id = a.archive_operation_id AND b.state_version = a.state_version
        JOIN semesters s ON s.id = a.semester_id AND s.state_version = a.state_version
        WHERE e.operation_id = edit_id AND e.semester_id = semester AND a.semester_id = semester
          AND ((b.participant_state = 'PENDING' AND s.archive_transition = 'ARCHIVING')
             OR (b.participant_state = 'DELETE_PREPARING' AND academic_semester_delete_preparing(semester))))
$$;

CREATE OR REPLACE FUNCTION guard_homework_edit_business_write()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
DECLARE row_value JSONB; semester BIGINT; edit_id UUID; blocked BOOLEAN; transfer_id UUID;
BEGIN
    row_value := CASE WHEN TG_OP = 'DELETE' THEN to_jsonb(OLD) ELSE to_jsonb(NEW) END;
    semester := (row_value ->> 'semester_id')::BIGINT;
    PERFORM pg_advisory_xact_lock(5452097, (semester % 2147483647)::INTEGER);
    IF TG_OP = 'DELETE' AND academic_semester_delete_authorized(semester) THEN RETURN OLD; END IF;
    SELECT NOT EXISTS (SELECT 1 FROM semesters s WHERE s.id = semester AND NOT s.is_archived
            AND s.archive_transition = 'NONE' AND NOT s.archive_release_pending)
        OR EXISTS (SELECT 1 FROM academic_semester_archive_barriers b WHERE b.semester_id = semester
            AND b.participant_state IN ('PENDING','READY','PREPARED_RESTORE','DELETE_PREPARING','DELETE_SEALED','DELETED')) INTO blocked;
    IF NOT blocked THEN
        IF TG_OP = 'DELETE' THEN RETURN OLD; END IF;
        RETURN NEW;
    END IF;
    edit_id := CASE WHEN TG_TABLE_NAME = 'homework_edit_operations' THEN (row_value ->> 'operation_id')::UUID
        ELSE nullif(current_setting('rutcampustrack.homework_edit_operation_id', TRUE), '')::UUID END;
    IF academic_homework_edit_epoch_admitted(edit_id, semester) THEN
        IF TG_TABLE_NAME = 'homework_edit_operations' AND TG_OP = 'UPDATE' THEN RETURN NEW; END IF;
        IF TG_OP = 'INSERT' AND EXISTS (SELECT 1 FROM homework_edit_operations e
            WHERE e.operation_id = edit_id AND e.state = 'FINALIZED' AND e.outcome = 'APPLIED'
              AND e.homework_id = (row_value ->> 'homework_id')::BIGINT
              AND e.actor_id = (row_value ->> 'actor_id')::BIGINT
              AND e.result_revision = coalesce((row_value ->> 'result_revision')::BIGINT, (row_value ->> 'revision')::BIGINT)
              AND e.result_snapshot = coalesce(row_value -> 'result_snapshot', row_value -> 'after_snapshot')) THEN RETURN NEW; END IF;
    END IF;
    transfer_id := nullif(current_setting('rutcampustrack.archive_transfer_operation_id', TRUE), '')::UUID;
    IF TG_TABLE_NAME = 'homework_edit_history' AND TG_OP = 'INSERT' AND row_value ->> 'action' = 'LESSON_TRANSFERRED'
       AND transfer_id IS NOT NULL AND nullif(current_setting('rutcampustrack.archive_transfer_semester_id', TRUE), '')::BIGINT = semester
       AND EXISTS (SELECT 1 FROM homeworks h WHERE h.id = (row_value ->> 'homework_id')::BIGINT AND h.semester_id = semester
           AND h.revision = (row_value ->> 'revision')::BIGINT AND h.binding_id = nullif(current_setting('rutcampustrack.archive_transfer_binding_id', TRUE), '')::BIGINT
           AND row_value -> 'after_snapshot' = jsonb_build_object('title', h.title, 'description', h.description, 'link', h.link,
               'bindingMode', h.binding_mode, 'lessonDate', h.lesson_date, 'lessonNumber', h.lesson_number)) THEN RETURN NEW; END IF;
    RAISE EXCEPTION 'homework edit is fenced by semester archive' USING ERRCODE = '55000';
END $$;
CREATE TRIGGER homework_edit_receipt_fence BEFORE INSERT OR UPDATE OR DELETE ON homework_edit_receipts
    FOR EACH ROW EXECUTE FUNCTION guard_homework_edit_business_write();
CREATE TRIGGER homework_edit_history_fence BEFORE INSERT OR UPDATE OR DELETE ON homework_edit_history
    FOR EACH ROW EXECUTE FUNCTION guard_homework_edit_business_write();
CREATE TRIGGER homework_edit_command_fence BEFORE INSERT OR UPDATE OR DELETE ON homework_edit_operations
    FOR EACH ROW EXECUTE FUNCTION guard_homework_edit_business_write();

CREATE OR REPLACE FUNCTION protect_homework_transfer_edit_supersession()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
    IF NEW.superseded_by_edit_operation_id IS NOT DISTINCT FROM OLD.superseded_by_edit_operation_id THEN RETURN NEW; END IF;
    IF NEW.superseded_by_edit_operation_id IS NULL AND academic_semester_delete_authorized(OLD.semester_id)
       AND (to_jsonb(NEW) - 'superseded_by_edit_operation_id') = (to_jsonb(OLD) - 'superseded_by_edit_operation_id') THEN RETURN NEW; END IF;
    IF NEW.superseded_by_edit_operation_id IS NULL AND NEW.operation_id IS DISTINCT FROM OLD.operation_id
       AND NEW.source_event_id IS DISTINCT FROM OLD.source_event_id THEN RETURN NEW; END IF;
    IF OLD.superseded_by_edit_operation_id IS NULL AND OLD.state = 'APPLIED'
       AND (to_jsonb(NEW) - 'superseded_by_edit_operation_id') = (to_jsonb(OLD) - 'superseded_by_edit_operation_id')
       AND EXISTS (SELECT 1 FROM homework_edit_operations e WHERE e.operation_id = NEW.superseded_by_edit_operation_id
           AND e.state = 'FINALIZED' AND e.outcome = 'APPLIED' AND e.binding_id = OLD.binding_id
           AND e.homework_id = OLD.homework_id AND e.group_id = OLD.group_id AND e.subject_id = OLD.subject_id
           AND e.semester_id = OLD.semester_id) THEN RETURN NEW; END IF;
    RAISE EXCEPTION 'transfer supersession requires the exact finalized homework edit';
END $$;
CREATE TRIGGER homework_transfer_edit_supersession BEFORE UPDATE ON homework_binding_transfer_markers
    FOR EACH ROW EXECUTE FUNCTION protect_homework_transfer_edit_supersession();

CREATE OR REPLACE FUNCTION retain_homework_edit_evidence()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
    IF TG_OP = 'DELETE' AND academic_semester_delete_authorized(OLD.semester_id) THEN RETURN OLD; END IF;
    RAISE EXCEPTION 'homework edit evidence is append-only';
END $$;
CREATE TRIGGER homework_history_append_only BEFORE UPDATE OR DELETE ON homework_edit_history
    FOR EACH ROW EXECUTE FUNCTION retain_homework_edit_evidence();
CREATE TRIGGER homework_edit_receipt_append_only BEFORE UPDATE OR DELETE ON homework_edit_receipts
    FOR EACH ROW EXECUTE FUNCTION retain_homework_edit_evidence();
CREATE TRIGGER homework_edit_admission_append_only BEFORE UPDATE OR DELETE ON homework_edit_archive_admissions
    FOR EACH ROW EXECUTE FUNCTION retain_homework_edit_evidence();

CREATE OR REPLACE FUNCTION protect_homework_edit_operation()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
    IF TG_OP = 'DELETE' AND academic_semester_delete_authorized(OLD.semester_id) THEN RETURN OLD; END IF;
    IF TG_OP = 'DELETE' THEN RAISE EXCEPTION 'homework edit operation is retained'; END IF;
    IF (to_jsonb(NEW) - ARRAY['state','outcome','result_snapshot','result_revision','finalized_at','attempts','next_attempt_at','last_failure'])
       IS DISTINCT FROM
       (to_jsonb(OLD) - ARRAY['state','outcome','result_snapshot','result_revision','finalized_at','attempts','next_attempt_at','last_failure']) THEN
        RAISE EXCEPTION 'homework edit command identity is immutable';
    END IF;
    IF OLD.state IN ('ACKNOWLEDGED', 'CANCELLED') THEN RAISE EXCEPTION 'homework edit outcome is terminal'; END IF;
    IF OLD.state = 'FINALIZED' AND (NEW.state NOT IN ('FINALIZED', 'ACKNOWLEDGED')
       OR NEW.outcome IS DISTINCT FROM OLD.outcome OR NEW.result_snapshot IS DISTINCT FROM OLD.result_snapshot
       OR NEW.result_revision IS DISTINCT FROM OLD.result_revision OR NEW.finalized_at IS DISTINCT FROM OLD.finalized_at) THEN
        RAISE EXCEPTION 'finalized homework edit result is immutable';
    END IF;
    IF OLD.state = 'PREPARED' AND NEW.state NOT IN ('PREPARED', 'FINALIZED', 'CANCELLED') THEN
        RAISE EXCEPTION 'invalid homework edit transition';
    END IF;
    RETURN NEW;
END $$;
CREATE TRIGGER homework_edit_operation_guard BEFORE UPDATE OR DELETE ON homework_edit_operations
    FOR EACH ROW EXECUTE FUNCTION protect_homework_edit_operation();

-- Retain the original immutable create/binding identity; freeze legacy accepted replay once.
CREATE OR REPLACE FUNCTION protect_homework_binding_identity()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
    IF NEW.binding_id IS DISTINCT FROM OLD.binding_id OR NEW.actor_id IS DISTINCT FROM OLD.actor_id
       OR NEW.request_key IS DISTINCT FROM OLD.request_key OR NEW.payload_hash IS DISTINCT FROM OLD.payload_hash
       OR NEW.published_by IS DISTINCT FROM OLD.published_by OR NEW.group_id IS DISTINCT FROM OLD.group_id
       OR NEW.subject_id IS DISTINCT FROM OLD.subject_id OR NEW.semester_id IS DISTINCT FROM OLD.semester_id THEN
        RAISE EXCEPTION 'homework publication identity is immutable';
    END IF;
    IF OLD.create_intent IS NOT NULL AND (NEW.create_intent IS DISTINCT FROM OLD.create_intent
       OR NEW.create_intent_kind IS DISTINCT FROM OLD.create_intent_kind) THEN
        RAISE EXCEPTION 'homework accepted create replay intent is immutable';
    END IF;
    IF OLD.create_intent IS NULL AND NEW.create_intent IS NOT NULL THEN
        IF NEW.create_intent_kind <> 'LEGACY_ACCEPTED_REPLAY'
           OR NEW.create_intent IS DISTINCT FROM jsonb_build_object(
                'groupId', OLD.group_id, 'subjectId', OLD.subject_id, 'semesterId', OLD.semester_id,
                'title', OLD.title, 'description', OLD.description, 'link', OLD.link,
                'bindingMode', OLD.binding_mode, 'lessonDate', OLD.lesson_date, 'lessonNumber', OLD.lesson_number)
           OR NOT EXISTS (SELECT 1 FROM homework_edit_receipts receipt
                WHERE receipt.homework_id = OLD.id AND receipt.result_revision = NEW.revision) THEN
            RAISE EXCEPTION 'legacy accepted replay requires its exact pre-edit fingerprint and receipt';
        END IF;
    END IF;
    IF OLD.publication_state = 'ACTIVE' AND NEW.publication_state NOT IN ('ACTIVE', 'ARCHIVED') THEN
        RAISE EXCEPTION 'active homework publication cannot be reverted to pending';
    END IF;
    IF OLD.publication_state = 'ARCHIVED' AND (NEW.publication_state <> 'ARCHIVED'
       OR NEW.title IS DISTINCT FROM OLD.title OR NEW.description IS DISTINCT FROM OLD.description
       OR NEW.link IS DISTINCT FROM OLD.link OR NEW.lesson_date IS DISTINCT FROM OLD.lesson_date
       OR NEW.lesson_number IS DISTINCT FROM OLD.lesson_number OR NEW.binding_mode IS DISTINCT FROM OLD.binding_mode
       OR NEW.revision IS DISTINCT FROM OLD.revision) THEN
        RAISE EXCEPTION 'archived homework is terminal and read-only';
    END IF;
    IF NEW.revision < OLD.revision THEN RAISE EXCEPTION 'homework revision cannot move backwards'; END IF;
    RETURN NEW;
END $$;

CREATE OR REPLACE FUNCTION academic_homework_edit_continuation_admitted(old_row JSONB, new_row JSONB, semester BIGINT)
RETURNS BOOLEAN LANGUAGE SQL STABLE AS $$
    SELECT EXISTS (SELECT 1 FROM homework_edit_operations edit
        JOIN homework_edit_archive_admissions admitted ON admitted.edit_operation_id = edit.operation_id
        JOIN academic_semester_archive_barriers barrier
          ON barrier.operation_id = admitted.archive_operation_id AND barrier.state_version = admitted.state_version
         AND barrier.semester_id = admitted.semester_id
        WHERE edit.operation_id = nullif(current_setting('rutcampustrack.homework_edit_operation_id', TRUE), '')::UUID
          AND edit.homework_id = (old_row ->> 'id')::BIGINT AND edit.semester_id = semester
          AND edit.command_hash = admitted.command_hash AND edit.state = 'FINALIZED' AND edit.outcome = 'APPLIED'
          AND academic_homework_edit_epoch_admitted(edit.operation_id, semester)
          AND barrier.participant_state IN ('PENDING', 'DELETE_PREPARING')
          AND old_row ->> 'publication_state' = 'ACTIVE' AND new_row ->> 'publication_state' = 'ACTIVE'
          AND (old_row ->> 'revision')::BIGINT = edit.expected_revision
          AND (new_row ->> 'revision')::BIGINT = edit.result_revision
          AND edit.result_snapshot = jsonb_build_object('title', new_row -> 'title', 'description', new_row -> 'description',
              'link', new_row -> 'link', 'bindingMode', new_row -> 'binding_mode',
              'lessonDate', new_row -> 'lesson_date', 'lessonNumber', new_row -> 'lesson_number')
          AND (old_row - ARRAY['title','description','link','lesson_date','lesson_number','binding_mode','revision',
                              'updated_at','due_reminder_sent_at','create_intent','create_intent_kind'])
              = (new_row - ARRAY['title','description','link','lesson_date','lesson_number','binding_mode','revision',
                                'updated_at','due_reminder_sent_at','create_intent','create_intent_kind']))
$$;

DO $$ DECLARE fn TEXT; updated TEXT;
BEGIN
    SELECT pg_get_functiondef('guard_academic_semester_archive_business_write()'::regprocedure) INTO fn;
    updated := replace(fn,
        'IF barrier_state IN (''PENDING'', ''READY'', ''PREPARED_RESTORE'', ''DELETE_PREPARING'', ''DELETE_SEALED'', ''DELETED'') OR authority_blocked THEN',
        'IF TG_TABLE_NAME = ''homeworks'' AND TG_OP = ''UPDATE''
            AND academic_homework_edit_continuation_admitted(old_row, new_row, target_semester_id) THEN CONTINUE; END IF;
         IF TG_TABLE_NAME = ''homework_binding_transfer_markers'' AND TG_OP = ''UPDATE''
            AND (new_row - ''superseded_by_edit_operation_id'') = (old_row - ''superseded_by_edit_operation_id'')
            AND ((academic_semester_delete_authorized(target_semester_id) AND new_row ->> ''superseded_by_edit_operation_id'' IS NULL)
              OR EXISTS (SELECT 1 FROM homework_edit_operations e
                  WHERE e.operation_id = (new_row ->> ''superseded_by_edit_operation_id'')::UUID
                    AND e.binding_id = (old_row ->> ''binding_id'')::BIGINT AND e.state = ''FINALIZED'' AND e.outcome = ''APPLIED''
                    AND academic_homework_edit_epoch_admitted(e.operation_id, target_semester_id))) THEN CONTINUE; END IF;
         IF barrier_state IN (''PENDING'', ''READY'', ''PREPARED_RESTORE'', ''DELETE_PREPARING'', ''DELETE_SEALED'', ''DELETED'') OR authority_blocked THEN');
    IF updated = fn THEN RAISE EXCEPTION 'V45 Academic archive guard anchor changed'; END IF;
    EXECUTE updated;
END $$;
